// URLs de logos de ESPN CDN (públicos, sin API key)
export const LOGOS: Record<string, string> = {
  // ── Liga MX ──────────────────────────────────────────────────────
  "América":               "https://a.espncdn.com/i/teamlogos/soccer/500/227.png",
  "Atlas":                 "https://a.espncdn.com/i/teamlogos/soccer/500/216.png",
  "Atlético San Luis":     "https://a.espncdn.com/i/teamlogos/soccer/500/15720.png",
  "Atlético de San Luis":  "https://a.espncdn.com/i/teamlogos/soccer/500/15720.png",
  "San Luis":              "https://a.espncdn.com/i/teamlogos/soccer/500/15720.png",
  "Cruz Azul":             "https://a.espncdn.com/i/teamlogos/soccer/500/218.png",
  "FC Juárez":             "https://a.espncdn.com/i/teamlogos/soccer/500/17851.png",
  "FC Juarez":             "https://a.espncdn.com/i/teamlogos/soccer/500/17851.png",
  "Guadalajara":           "https://a.espncdn.com/i/teamlogos/soccer/500/219.png",
  "León":                  "https://a.espncdn.com/i/teamlogos/soccer/500/228.png",
  "Mazatlán":              "https://a.espncdn.com/i/teamlogos/soccer/500/20702.png",
  "Mazatlán FC":           "https://a.espncdn.com/i/teamlogos/soccer/500/20702.png",
  "Monterrey":             "https://a.espncdn.com/i/teamlogos/soccer/500/220.png",
  "Necaxa":                "https://a.espncdn.com/i/teamlogos/soccer/500/229.png",
  "Pachuca":               "https://a.espncdn.com/i/teamlogos/soccer/500/234.png",
  "Puebla":                "https://a.espncdn.com/i/teamlogos/soccer/500/231.png",
  "Pumas UNAM":            "https://a.espncdn.com/i/teamlogos/soccer/500/233.png",
  "Pumas":                 "https://a.espncdn.com/i/teamlogos/soccer/500/233.png",
  "Querétaro":             "https://a.espncdn.com/i/teamlogos/soccer/500/222.png",
  "Santos Laguna":         "https://a.espncdn.com/i/teamlogos/soccer/500/225.png",
  "Tigres UANL":           "https://a.espncdn.com/i/teamlogos/soccer/500/232.png",
  "Tigres":                "https://a.espncdn.com/i/teamlogos/soccer/500/232.png",
  "Tijuana":               "https://a.espncdn.com/i/teamlogos/soccer/500/10125.png",
  "Toluca":                "https://a.espncdn.com/i/teamlogos/soccer/500/223.png",

  // ── Premier League ────────────────────────────────────────────────
  "Arsenal":               "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
  "Liverpool":             "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
  "Manchester City":       "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "Chelsea":               "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
  "Aston Villa":           "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
  "Tottenham":             "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "Tottenham Hotspur":     "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "Manchester United":     "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "Newcastle":             "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "West Ham":              "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
  "Brighton":              "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "Everton":               "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
  "Fulham":                "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
  "Nottingham Forest":     "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "Brentford":             "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
  "Wolverhampton":         "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
  "Crystal Palace":        "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "Leicester City":        "https://a.espncdn.com/i/teamlogos/soccer/500/375.png",
  "Ipswich Town":          "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
  "Southampton":           "https://a.espncdn.com/i/teamlogos/soccer/500/376.png",
  "Bournemouth":           "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "Sunderland":            "https://a.espncdn.com/i/teamlogos/soccer/500/405.png",

  // ── La Liga ───────────────────────────────────────────────────────
  "Real Madrid":           "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
  "Barcelona":             "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
  "Atlético Madrid":       "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "Villarreal":            "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
  "Sevilla":               "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
  "Athletic Club":         "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "Real Sociedad":         "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
  "Real Betis":            "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "Valencia":              "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
  "Osasuna":               "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
  "Girona":                "https://a.espncdn.com/i/teamlogos/soccer/500/9812.png",
  "Celta Vigo":            "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
  "Rayo Vallecano":        "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "Getafe":                "https://a.espncdn.com/i/teamlogos/soccer/500/3842.png",
  "Deportivo Alavés":      "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "Mallorca":              "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
  "Leganés":               "https://a.espncdn.com/i/teamlogos/soccer/500/17534.png",
  "Espanyol":              "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
  "Las Palmas":            "https://a.espncdn.com/i/teamlogos/soccer/500/5593.png",
  "Valladolid":            "https://a.espncdn.com/i/teamlogos/soccer/500/95.png",
  "Real Valladolid":       "https://a.espncdn.com/i/teamlogos/soccer/500/95.png",

  // ── La Liga / Segunda División (equipos adicionales) ──────────────
  "Levante":               "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "Levante UD":            "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "Elche":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "Elche CF":              "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "Real Oviedo":           "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
  "Oviedo":                "https://a.espncdn.com/i/teamlogos/soccer/500/92.png",
  "Cádiz":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3756.png",
  "Cádiz CF":              "https://a.espncdn.com/i/teamlogos/soccer/500/3756.png",
  "Granada":               "https://a.espncdn.com/i/teamlogos/soccer/500/746.png",
  "Granada CF":            "https://a.espncdn.com/i/teamlogos/soccer/500/746.png",
  "Almería":               "https://a.espncdn.com/i/teamlogos/soccer/500/2878.png",
  "UD Almería":            "https://a.espncdn.com/i/teamlogos/soccer/500/2878.png",
  "Málaga":                "https://a.espncdn.com/i/teamlogos/soccer/500/768.png",
  "Málaga CF":             "https://a.espncdn.com/i/teamlogos/soccer/500/768.png",
  "Sporting Gijón":        "https://a.espncdn.com/i/teamlogos/soccer/500/769.png",
  "Sporting de Gijón":     "https://a.espncdn.com/i/teamlogos/soccer/500/769.png",
  "Deportivo":             "https://a.espncdn.com/i/teamlogos/soccer/500/247.png",
  "Deportivo La Coruña":   "https://a.espncdn.com/i/teamlogos/soccer/500/247.png",
  "RC Deportivo":          "https://a.espncdn.com/i/teamlogos/soccer/500/247.png",
  "Huesca":                "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "SD Huesca":             "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "Zaragoza":              "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "Real Zaragoza":         "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "Eibar":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3839.png",
  "SD Eibar":              "https://a.espncdn.com/i/teamlogos/soccer/500/3839.png",
  "Burgos":                "https://a.espncdn.com/i/teamlogos/soccer/500/3750.png",
  "Burgos CF":             "https://a.espncdn.com/i/teamlogos/soccer/500/3750.png",
  "Racing Santander":      "https://a.espncdn.com/i/teamlogos/soccer/500/755.png",
  "Racing Ferrol":         "https://a.espncdn.com/i/teamlogos/soccer/500/9815.png",
  "Castellón":             "https://a.espncdn.com/i/teamlogos/soccer/500/9803.png",
  "CD Castellón":          "https://a.espncdn.com/i/teamlogos/soccer/500/9803.png",
  "Córdoba":               "https://a.espncdn.com/i/teamlogos/soccer/500/750.png",
  "Córdoba CF":            "https://a.espncdn.com/i/teamlogos/soccer/500/750.png",
  "FC Andorra":            "https://a.espncdn.com/i/teamlogos/soccer/500/17032.png",
  "Andorra":               "https://a.espncdn.com/i/teamlogos/soccer/500/17032.png",
  "Tenerife":              "https://a.espncdn.com/i/teamlogos/soccer/500/3757.png",
  "CD Tenerife":           "https://a.espncdn.com/i/teamlogos/soccer/500/3757.png",
  "Mirandés":              "https://a.espncdn.com/i/teamlogos/soccer/500/9808.png",
  "Alcorcón":              "https://a.espncdn.com/i/teamlogos/soccer/500/9807.png",
  "Lugo":                  "https://a.espncdn.com/i/teamlogos/soccer/500/9804.png",
  "Ponferradina":          "https://a.espncdn.com/i/teamlogos/soccer/500/9806.png",
  "Cartagena":             "https://a.espncdn.com/i/teamlogos/soccer/500/9814.png",
  "FC Cartagena":          "https://a.espncdn.com/i/teamlogos/soccer/500/9814.png",

  // ── Ligue 1 (Francia) ─────────────────────────────────────────────
  "Olympique de Marseille":   "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "Marseille":                "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "Olympique Lyonnais":       "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "Lyon":                     "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "AS Monaco":                "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "Lille OSC":                "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
  "OGC Nice":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2502.png",
  "Nice":                     "https://a.espncdn.com/i/teamlogos/soccer/500/2502.png",
  "RC Lens":                  "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "Lens":                     "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "Stade Rennais":            "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "Rennes":                   "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "Strasbourg":               "https://a.espncdn.com/i/teamlogos/soccer/500/180.png",
  "Nantes":                   "https://a.espncdn.com/i/teamlogos/soccer/500/165.png",
  "Montpellier":              "https://a.espncdn.com/i/teamlogos/soccer/500/274.png",
  "Reims":                    "https://a.espncdn.com/i/teamlogos/soccer/500/171.png",
  "Toulouse FC":              "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  "Toulouse":                 "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  "Le Havre":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3236.png",
  "Lorient":                  "https://a.espncdn.com/i/teamlogos/soccer/500/273.png",
  "Auxerre":                  "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "Angers":                   "https://a.espncdn.com/i/teamlogos/soccer/500/7868.png",
  "Saint-Étienne":            "https://a.espncdn.com/i/teamlogos/soccer/500/178.png",
  "Paris FC":                 "https://a.espncdn.com/i/teamlogos/soccer/500/5591.png",

  // ── Brasileirão ───────────────────────────────────────────────────
  // IDs reales de ESPN soccer
  "Flamengo":                 "https://a.espncdn.com/i/teamlogos/soccer/500/819.png",
  "Palmeiras":                "https://a.espncdn.com/i/teamlogos/soccer/500/2029.png",
  "Atlético Mineiro":         "https://a.espncdn.com/i/teamlogos/soccer/500/7632.png",
  "Fluminense":               "https://a.espncdn.com/i/teamlogos/soccer/500/3445.png",
  "Botafogo":                 "https://a.espncdn.com/i/teamlogos/soccer/500/6086.png",
  "São Paulo":                "https://a.espncdn.com/i/teamlogos/soccer/500/2026.png",
  "Corinthians":              "https://a.espncdn.com/i/teamlogos/soccer/500/874.png",
  "Vasco da Gama":            "https://a.espncdn.com/i/teamlogos/soccer/500/3454.png",
  "Vasco":                    "https://a.espncdn.com/i/teamlogos/soccer/500/3454.png",
  "Internacional":            "https://a.espncdn.com/i/teamlogos/soccer/500/1936.png",
  "Grêmio":                   "https://a.espncdn.com/i/teamlogos/soccer/500/6273.png",
  "Belgrano (Córdoba)":      "https://a.espncdn.com/i/teamlogos/soccer/500/4.png",
  "CA Belgrano":             "https://a.espncdn.com/i/teamlogos/soccer/500/4.png",
  "Santos FC":                "https://a.espncdn.com/i/teamlogos/soccer/500/2674.png",
  "Santos":                   "https://a.espncdn.com/i/teamlogos/soccer/500/2674.png", // → Santos FC Brasil ("Santos Laguna" ya está en Liga MX arriba)
  "Athletico Paranaense":     "https://a.espncdn.com/i/teamlogos/soccer/500/3458.png",
  "Atlético Paranaense":      "https://a.espncdn.com/i/teamlogos/soccer/500/3458.png",
  "Cruzeiro":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2022.png",
  "Bahia":                    "https://a.espncdn.com/i/teamlogos/soccer/500/9967.png",
  "Fortaleza":                "https://a.espncdn.com/i/teamlogos/soccer/500/6272.png",
  "Cuiabá":                   "https://a.espncdn.com/i/teamlogos/soccer/500/17313.png",
  "Red Bull Bragantino":      "https://a.espncdn.com/i/teamlogos/soccer/500/6079.png",
  "Bragantino":               "https://a.espncdn.com/i/teamlogos/soccer/500/6079.png",
  "Goiás":                    "https://a.espncdn.com/i/teamlogos/soccer/500/3395.png",
  "Chapecoense":              "https://a.espncdn.com/i/teamlogos/soccer/500/9318.png",
  "Juventude":                "https://a.espncdn.com/i/teamlogos/soccer/500/6270.png",
  "Ceará":                    "https://a.espncdn.com/i/teamlogos/soccer/500/9969.png",
  "Sport Recife":             "https://a.espncdn.com/i/teamlogos/soccer/500/7635.png",
  "Sport":                    "https://a.espncdn.com/i/teamlogos/soccer/500/7635.png",
  "Vitória":                  "https://a.espncdn.com/i/teamlogos/soccer/500/3457.png",
  "Criciúma":                 "https://a.espncdn.com/i/teamlogos/soccer/500/9971.png",
  "Mirassol":                 "https://a.espncdn.com/i/teamlogos/soccer/500/9169.png",
  "Coritiba":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3456.png",

  // ── Liga Argentina ────────────────────────────────────────────────
  // IDs reales de ESPN soccer
  "Boca Juniors":             "https://a.espncdn.com/i/teamlogos/soccer/500/5.png",
  "River Plate":              "https://a.espncdn.com/i/teamlogos/soccer/500/16.png",
  "Racing Club":              "https://a.espncdn.com/i/teamlogos/soccer/500/15.png",
  "San Lorenzo":              "https://a.espncdn.com/i/teamlogos/soccer/500/18.png",
  "Independiente":            "https://a.espncdn.com/i/teamlogos/soccer/500/11.png",
  "Estudiantes":              "https://a.espncdn.com/i/teamlogos/soccer/500/8.png",
  "Estudiantes LP":           "https://a.espncdn.com/i/teamlogos/soccer/500/8.png",
  "Vélez Sársfield":          "https://a.espncdn.com/i/teamlogos/soccer/500/21.png",
  "Vélez":                    "https://a.espncdn.com/i/teamlogos/soccer/500/21.png",
  "Lanús":                    "https://a.espncdn.com/i/teamlogos/soccer/500/12.png",
  "Talleres":                 "https://a.espncdn.com/i/teamlogos/soccer/500/19.png",
  "Huracán":                  "https://a.espncdn.com/i/teamlogos/soccer/500/10.png",
  "Banfield":                 "https://a.espncdn.com/i/teamlogos/soccer/500/235.png",
  "Defensa y Justicia":       "https://a.espncdn.com/i/teamlogos/soccer/500/8950.png",
  "Newell's Old Boys":        "https://a.espncdn.com/i/teamlogos/soccer/500/14.png",
  "Rosario Central":          "https://a.espncdn.com/i/teamlogos/soccer/500/17.png",
  "Argentinos Juniors":       "https://a.espncdn.com/i/teamlogos/soccer/500/3.png",
  "Colón":                    "https://a.espncdn.com/i/teamlogos/soccer/500/6.png",
  "Gimnasia LP":              "https://a.espncdn.com/i/teamlogos/soccer/500/9.png",
  "Tigre":                    "https://a.espncdn.com/i/teamlogos/soccer/500/7767.png",
  "Godoy Cruz":               "https://a.espncdn.com/i/teamlogos/soccer/500/6756.png",
  "Unión Santa Fe":           "https://a.espncdn.com/i/teamlogos/soccer/500/20.png",
  "Platense":                 "https://a.espncdn.com/i/teamlogos/soccer/500/7764.png",
  "Sarmiento":                "https://a.espncdn.com/i/teamlogos/soccer/500/10158.png",
  "Belgrano":                 "https://a.espncdn.com/i/teamlogos/soccer/500/4.png",
  "Instituto":                "https://a.espncdn.com/i/teamlogos/soccer/500/2975.png",
  "San Martín SJ":            "https://a.espncdn.com/i/teamlogos/soccer/500/7768.png",
  "Barracas Central":         "https://a.espncdn.com/i/teamlogos/soccer/500/10060.png",
  "Riestra":                  "https://a.espncdn.com/i/teamlogos/soccer/500/17702.png",
  "Atlético Tucumán":         "https://a.espncdn.com/i/teamlogos/soccer/500/9785.png",
  "Tucumán":                  "https://a.espncdn.com/i/teamlogos/soccer/500/9785.png",

  // ── Mundial — Selecciones nacionales ──────────────────────────────
  // ESPN countries CDN (ruta diferente: /countries/ en lugar de /soccer/)
  // CONCACAF / Hosts
  "México":                   "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
  "Estados Unidos":           "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
  "USA":                      "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
  "Canadá":                   "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
  "Panamá":                   "https://a.espncdn.com/i/teamlogos/countries/500/pan.png",
  "Honduras":                 "https://a.espncdn.com/i/teamlogos/countries/500/hon.png",
  "Jamaica":                  "https://a.espncdn.com/i/teamlogos/countries/500/jam.png",
  "El Salvador":              "https://a.espncdn.com/i/teamlogos/countries/500/slv.png",
  "Cuba":                     "https://a.espncdn.com/i/teamlogos/countries/500/cub.png",
  "Costa Rica":               "https://a.espncdn.com/i/teamlogos/countries/500/crc.png",
  "Curazao":                  "https://a.espncdn.com/i/teamlogos/countries/500/cuw.png",
  "Curaçao":                  "https://a.espncdn.com/i/teamlogos/countries/500/cuw.png",
  "Curacao":                  "https://a.espncdn.com/i/teamlogos/countries/500/cuw.png",
  // CONMEBOL
  "Argentina":                "https://a.espncdn.com/i/teamlogos/countries/500/arg.png",
  "Brasil":                   "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
  "Uruguay":                  "https://a.espncdn.com/i/teamlogos/countries/500/uru.png",
  "Colombia":                 "https://a.espncdn.com/i/teamlogos/countries/500/col.png",
  "Ecuador":                  "https://a.espncdn.com/i/teamlogos/countries/500/ecu.png",
  "Venezuela":                "https://a.espncdn.com/i/teamlogos/countries/500/ven.png",
  "Chile":                    "https://a.espncdn.com/i/teamlogos/countries/500/chi.png",
  "Perú":                     "https://a.espncdn.com/i/teamlogos/countries/500/per.png",
  "Paraguay":                 "https://a.espncdn.com/i/teamlogos/countries/500/par.png",
  "Bolivia":                  "https://a.espncdn.com/i/teamlogos/countries/500/bol.png",
  "Surinam":                  "https://a.espncdn.com/i/teamlogos/countries/500/sur.png",
  // UEFA
  "España":                   "https://a.espncdn.com/i/teamlogos/countries/500/esp.png",
  "Francia":                  "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
  "Alemania":                 "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
  "Portugal":                 "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
  "Inglaterra":               "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
  "Italia":                   "https://a.espncdn.com/i/teamlogos/countries/500/ita.png",
  "Países Bajos":             "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
  "Holanda":                  "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
  "Bélgica":                  "https://a.espncdn.com/i/teamlogos/countries/500/bel.png",
  "Croacia":                  "https://a.espncdn.com/i/teamlogos/countries/500/cro.png",
  "Suiza":                    "https://a.espncdn.com/i/teamlogos/countries/500/sui.png",
  "Polonia":                  "https://a.espncdn.com/i/teamlogos/countries/500/pol.png",
  "Türkiye":                  "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
  "Turquía":                  "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
  "Dinamarca":                "https://a.espncdn.com/i/teamlogos/countries/500/den.png",
  "Austria":                  "https://a.espncdn.com/i/teamlogos/countries/500/aut.png",
  "Suecia":                   "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
  "Serbia":                   "https://a.espncdn.com/i/teamlogos/countries/500/srb.png",
  "Escocia":                  "https://a.espncdn.com/i/teamlogos/countries/500/sco.png",
  "Gales":                    "https://a.espncdn.com/i/teamlogos/countries/500/wal.png",
  "Rep. Checa":               "https://a.espncdn.com/i/teamlogos/countries/500/cze.png",
  "Rumania":                  "https://a.espncdn.com/i/teamlogos/countries/500/rou.png",
  "Grecia":                   "https://a.espncdn.com/i/teamlogos/countries/500/gre.png",
  "Hungría":                  "https://a.espncdn.com/i/teamlogos/countries/500/hun.png",
  "Ucrania":                  "https://a.espncdn.com/i/teamlogos/countries/500/ukr.png",
  "Georgia":                  "https://a.espncdn.com/i/teamlogos/countries/500/geo.png",
  "Eslovaquia":               "https://a.espncdn.com/i/teamlogos/countries/500/svk.png",
  "Eslovenia":                "https://a.espncdn.com/i/teamlogos/countries/500/svn.png",
  "Albania":                  "https://a.espncdn.com/i/teamlogos/countries/500/alb.png",
  "Noruega":                  "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
  "Islandia":                 "https://a.espncdn.com/i/teamlogos/countries/500/isl.png",
  "Finlandia":                "https://a.espncdn.com/i/teamlogos/countries/500/fin.png",
  "Luxemburgo":               "https://a.espncdn.com/i/teamlogos/countries/500/lux.png",
  "Bosnia-Herzegovina":       "https://a.espncdn.com/i/teamlogos/countries/500/bih.png",
  // CAF
  "Marruecos":                "https://a.espncdn.com/i/teamlogos/countries/500/mar.png",
  "Senegal":                  "https://a.espncdn.com/i/teamlogos/countries/500/sen.png",
  "Nigeria":                  "https://a.espncdn.com/i/teamlogos/countries/500/nga.png",
  "Egipto":                   "https://a.espncdn.com/i/teamlogos/countries/500/egy.png",
  "Sudáfrica":                "https://a.espncdn.com/i/teamlogos/countries/500/rsa.png",
  "Camerún":                  "https://a.espncdn.com/i/teamlogos/countries/500/cmr.png",
  "Costa de Marfil":          "https://a.espncdn.com/i/teamlogos/countries/500/civ.png",
  "Argelia":                  "https://a.espncdn.com/i/teamlogos/countries/500/alg.png",
  "Túnez":                    "https://a.espncdn.com/i/teamlogos/countries/500/tun.png",
  "R.D. Congo":               "https://a.espncdn.com/i/teamlogos/countries/500/cod.png",
  "Mali":                     "https://a.espncdn.com/i/teamlogos/countries/500/mli.png",
  "Guinea":                   "https://a.espncdn.com/i/teamlogos/countries/500/gui.png",
  "Ghana":                    "https://a.espncdn.com/i/teamlogos/countries/500/gha.png",
  // AFC
  "Japón":                    "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
  "Corea del Sur":            "https://a.espncdn.com/i/teamlogos/countries/500/kor.png",
  "Australia":                "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
  "Arabia Saudita":           "https://a.espncdn.com/i/teamlogos/countries/500/ksa.png",
  "Irán":                     "https://a.espncdn.com/i/teamlogos/countries/500/irn.png",
  "Irak":                     "https://a.espncdn.com/i/teamlogos/countries/500/irq.png",
  "Uzbekistán":               "https://a.espncdn.com/i/teamlogos/countries/500/uzb.png",
  "Jordania":                 "https://a.espncdn.com/i/teamlogos/countries/500/jor.png",
  "Omán":                     "https://a.espncdn.com/i/teamlogos/countries/500/oma.png",
  "Indonesia":                "https://a.espncdn.com/i/teamlogos/countries/500/idn.png",
  "Palestina":                "https://a.espncdn.com/i/teamlogos/countries/500/pal.png",
  "Qatar":                    "https://a.espncdn.com/i/teamlogos/countries/500/qat.png",
  // OFC
  "Nueva Zelanda":            "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",


  "Burnley":               "https://a.espncdn.com/i/teamlogos/soccer/500/379.png",
  "Leeds United":          "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",

  // ── Serie A ───────────────────────────────────────────────────────
  "Inter":                    "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "AS Roma":                  "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "SS Lazio":                 "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "Fiorentina":               "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "ACF Fiorentina":           "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "Torino":                   "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "Torino FC":                "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "Bologna":                  "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "Bologna FC 1909":          "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "Udinese":                  "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  "Udinese Calcio":           "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  "Hellas Verona":            "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
  "Verona":                   "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
  "Hellas Verona FC":         "https://a.espncdn.com/i/teamlogos/soccer/500/119.png",
  "Genoa":                    "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "Genoa CFC":                "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "Parma":                    "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
  "Parma Calcio 1913":        "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
  "Lecce":                    "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "US Lecce":                 "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "Cagliari":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "Cagliari Calcio":          "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "Empoli":                   "https://a.espncdn.com/i/teamlogos/soccer/500/2574.png",
  "FC Empoli":                "https://a.espncdn.com/i/teamlogos/soccer/500/2574.png",
  "Monza":                    "https://a.espncdn.com/i/teamlogos/soccer/500/4007.png",
  "AC Monza":                 "https://a.espncdn.com/i/teamlogos/soccer/500/4007.png",
  "Como":                     "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
  "Como 1907":                "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
  "Venezia":                  "https://a.espncdn.com/i/teamlogos/soccer/500/17530.png",
  "Venezia FC":               "https://a.espncdn.com/i/teamlogos/soccer/500/17530.png",
  "Salernitana":              "https://a.espncdn.com/i/teamlogos/soccer/500/151.png",
  "US Salernitana":           "https://a.espncdn.com/i/teamlogos/soccer/500/151.png",
  "Cremonese":                "https://a.espncdn.com/i/teamlogos/soccer/500/4050.png",
  "US Cremonese":             "https://a.espncdn.com/i/teamlogos/soccer/500/4050.png",
  "Pisa":                     "https://a.espncdn.com/i/teamlogos/soccer/500/3956.png",
  "AC Pisa":                  "https://a.espncdn.com/i/teamlogos/soccer/500/3956.png",
  "Sassuolo":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",
  "US Sassuolo":              "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",

  // ── Bundesliga ─────────────────────────────────────── IDs verificados de ESPN API
  "Eintracht Frankfurt":      "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "Wolfsburg":                "https://a.espncdn.com/i/teamlogos/soccer/500/138.png",
  "VfL Wolfsburg":            "https://a.espncdn.com/i/teamlogos/soccer/500/138.png",
  "Stuttgart":                "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "VfB Stuttgart":            "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "Borussia Mönchengladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "Gladbach":                 "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "Mönchengladbach":          "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "Köln":                     "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "FC Köln":                  "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "FC Cologne":               "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "Werder Bremen":            "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "SV Werder Bremen":         "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "SC Freiburg":              "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "Freiburg":                 "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "Hoffenheim":               "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "TSG Hoffenheim":           "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "TSG 1899 Hoffenheim":      "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "Augsburg":                 "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "FC Augsburg":              "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "Mainz":                    "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "Mainz 05":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "1. FSV Mainz 05":          "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "Union Berlin":             "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "1. FC Union Berlin":       "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "St. Pauli":                "https://a.espncdn.com/i/teamlogos/soccer/500/270.png",
  "FC St. Pauli":             "https://a.espncdn.com/i/teamlogos/soccer/500/270.png",
  "Heidenheim":               "https://a.espncdn.com/i/teamlogos/soccer/500/6418.png",
  "1. FC Heidenheim":         "https://a.espncdn.com/i/teamlogos/soccer/500/6418.png",
  "1. FC Heidenheim 1846":    "https://a.espncdn.com/i/teamlogos/soccer/500/6418.png",
  "Holstein Kiel":            "https://a.espncdn.com/i/teamlogos/soccer/500/789.png",

  // ── MLS ──────────────────────────────────────────────────────────
  "Inter Miami CF":           "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png",
  "Inter Miami":              "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png",
  "LA Galaxy":                "https://a.espncdn.com/i/teamlogos/soccer/500/187.png",
  "LAFC":                     "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png",
  "Los Angeles FC":           "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png",
  "Seattle Sounders FC":      "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png",
  "Seattle Sounders":         "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png",
  "Portland Timbers":         "https://a.espncdn.com/i/teamlogos/soccer/500/9723.png",
  "Atlanta United FC":        "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png",
  "Atlanta United":           "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png",
  "New York City FC":         "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png",
  "NYCFC":                    "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png",
  "Red Bull New York":        "https://a.espncdn.com/i/teamlogos/soccer/500/190.png",
  "New York Red Bulls":       "https://a.espncdn.com/i/teamlogos/soccer/500/190.png",
  "Philadelphia Union":       "https://a.espncdn.com/i/teamlogos/soccer/500/10739.png",
  "FC Cincinnati":            "https://a.espncdn.com/i/teamlogos/soccer/500/18267.png",
  "Columbus Crew":            "https://a.espncdn.com/i/teamlogos/soccer/500/183.png",
  "Chicago Fire FC":          "https://a.espncdn.com/i/teamlogos/soccer/500/182.png",
  "Chicago Fire":             "https://a.espncdn.com/i/teamlogos/soccer/500/182.png",
  "D.C. United":              "https://a.espncdn.com/i/teamlogos/soccer/500/193.png",
  "DC United":                "https://a.espncdn.com/i/teamlogos/soccer/500/193.png",
  "Toronto FC":               "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png",
  "CF Montréal":              "https://a.espncdn.com/i/teamlogos/soccer/500/9720.png",
  "CF Montreal":              "https://a.espncdn.com/i/teamlogos/soccer/500/9720.png",
  "New England Revolution":   "https://a.espncdn.com/i/teamlogos/soccer/500/189.png",
  "Orlando City SC":          "https://a.espncdn.com/i/teamlogos/soccer/500/12011.png",
  "Orlando City":             "https://a.espncdn.com/i/teamlogos/soccer/500/12011.png",
  "Nashville SC":             "https://a.espncdn.com/i/teamlogos/soccer/500/18986.png",
  "Charlotte FC":             "https://a.espncdn.com/i/teamlogos/soccer/500/21300.png",
  "Austin FC":                "https://a.espncdn.com/i/teamlogos/soccer/500/20906.png",
  "FC Dallas":                "https://a.espncdn.com/i/teamlogos/soccer/500/185.png",
  "Houston Dynamo FC":        "https://a.espncdn.com/i/teamlogos/soccer/500/6077.png",
  "Houston Dynamo":           "https://a.espncdn.com/i/teamlogos/soccer/500/6077.png",
  "Sporting Kansas City":     "https://a.espncdn.com/i/teamlogos/soccer/500/186.png",
  "Colorado Rapids":          "https://a.espncdn.com/i/teamlogos/soccer/500/184.png",
  "Real Salt Lake":           "https://a.espncdn.com/i/teamlogos/soccer/500/4771.png",
  "San Jose Earthquakes":     "https://a.espncdn.com/i/teamlogos/soccer/500/191.png",
  "Vancouver Whitecaps":      "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png",
  "Vancouver Whitecaps FC":   "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png",
  "Minnesota United FC":      "https://a.espncdn.com/i/teamlogos/soccer/500/17362.png",
  "Minnesota United":         "https://a.espncdn.com/i/teamlogos/soccer/500/17362.png",
  "St. Louis CITY SC":        "https://a.espncdn.com/i/teamlogos/soccer/500/21812.png",
  "San Diego FC":             "https://a.espncdn.com/i/teamlogos/soccer/500/22529.png",

  // ── CONCACAF — equipos centroamericanos ─────────────────────────────
  // IDs verificados desde ESPN API concacaf.champions
  "Saprissa":              "https://a.espncdn.com/i/teamlogos/soccer/500/1828.png",
  "Deportivo Saprissa":    "https://a.espncdn.com/i/teamlogos/soccer/500/1828.png",
  "Alajuelense":           "https://a.espncdn.com/i/teamlogos/soccer/500/5760.png",
  "LD Alajuelense":        "https://a.espncdn.com/i/teamlogos/soccer/500/5760.png",
  "Comunicaciones":        "https://a.espncdn.com/i/teamlogos/soccer/500/5750.png",
  "Real España":           "https://a.espncdn.com/i/teamlogos/soccer/500/5753.png",
  "Olimpia Honduras":      "https://a.espncdn.com/i/teamlogos/soccer/500/5752.png",
  "Motagua":               "https://a.espncdn.com/i/teamlogos/soccer/500/5754.png",
  "Forge FC":              "https://a.espncdn.com/i/teamlogos/soccer/500/20130.png",
  "Pacific FC":            "https://a.espncdn.com/i/teamlogos/soccer/500/21742.png",

  // ── Copa Libertadores — equipos adicionales ── IDs verificados de ESPN API
  "Nacional":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2684.png",
  "Club Nacional de Football": "https://a.espncdn.com/i/teamlogos/soccer/500/2684.png",
  "Peñarol":                  "https://a.espncdn.com/i/teamlogos/soccer/500/2683.png",
  "Club Atlético Peñarol":    "https://a.espncdn.com/i/teamlogos/soccer/500/2683.png",
  "Colo Colo":                "https://a.espncdn.com/i/teamlogos/soccer/500/885.png",
  "Club Colo-Colo":           "https://a.espncdn.com/i/teamlogos/soccer/500/885.png",
  "Universidad de Chile":     "https://a.espncdn.com/i/teamlogos/soccer/500/5649.png",
  "LDU Quito":                "https://a.espncdn.com/i/teamlogos/soccer/500/4816.png",
  "Liga de Quito":            "https://a.espncdn.com/i/teamlogos/soccer/500/4816.png",
  "Liga Deportiva Universitaria": "https://a.espncdn.com/i/teamlogos/soccer/500/4816.png",
  "Independiente del Valle":  "https://a.espncdn.com/i/teamlogos/soccer/500/17086.png",
  "Olimpia":                  "https://a.espncdn.com/i/teamlogos/soccer/500/5752.png",
  "Cerro Porteño":            "https://a.espncdn.com/i/teamlogos/soccer/500/2671.png",
  "Club Cerro Porteño":       "https://a.espncdn.com/i/teamlogos/soccer/500/2671.png",
  "Libertad":                 "https://a.espncdn.com/i/teamlogos/soccer/500/2670.png",
  "Club Libertad":            "https://a.espncdn.com/i/teamlogos/soccer/500/2670.png",
  "Bolívar":                  "https://a.espncdn.com/i/teamlogos/soccer/500/2681.png",
  "Club Bolívar":             "https://a.espncdn.com/i/teamlogos/soccer/500/2681.png",
  "The Strongest":            "https://a.espncdn.com/i/teamlogos/soccer/500/5731.png",
  "Universitario":            "https://a.espncdn.com/i/teamlogos/soccer/500/2685.png",
  "Universitario de Deportes": "https://a.espncdn.com/i/teamlogos/soccer/500/2685.png",
  "Atlético Nacional":        "https://a.espncdn.com/i/teamlogos/soccer/500/5609.png",
  "Millonarios":              "https://a.espncdn.com/i/teamlogos/soccer/500/5607.png",
  "Junior":                   "https://a.espncdn.com/i/teamlogos/soccer/500/4815.png",
  "Atlético Junior":          "https://a.espncdn.com/i/teamlogos/soccer/500/4815.png",
  "Deportivo Táchira":        "https://a.espncdn.com/i/teamlogos/soccer/500/4818.png",
  "Caracas FC":               "https://a.espncdn.com/i/teamlogos/soccer/500/4811.png",
  "Barcelona SC":             "https://a.espncdn.com/i/teamlogos/soccer/500/2686.png",

  // ── UEFA Champions League ─────────────────────────────────────────
  "Bayern Munich":         "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "PSG":                   "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "Paris Saint-Germain":   "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "Juventus":              "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
  "Inter Milan":           "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "AC Milan":              "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "Borussia Dortmund":     "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "Bayer Leverkusen":      "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "RB Leipzig":            "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "RasenBallsport Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "Ajax":                  "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "Porto":                 "https://a.espncdn.com/i/teamlogos/soccer/500/235.png",
  "Benfica":               "https://a.espncdn.com/i/teamlogos/soccer/500/236.png",
  "Sporting CP":           "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "PSV":                   "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "Feyenoord":             "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
  "Club Brugge":           "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
  "Napoli":                "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "SSC Napoli":            "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "Roma":                  "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "Lazio":                 "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "Celtic":                "https://a.espncdn.com/i/teamlogos/soccer/500/254.png",
  "Galatasaray":           "https://a.espncdn.com/i/teamlogos/soccer/500/2832.png",
  "Shakhtar Donetsk":      "https://a.espncdn.com/i/teamlogos/soccer/500/381.png",
  "Red Bull Salzburg":     "https://a.espncdn.com/i/teamlogos/soccer/500/2790.png",
  "Monaco":                "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "Atalanta":              "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
  "Lille":                 "https://a.espncdn.com/i/teamlogos/soccer/500/162.png",
  "Brest":                 "https://a.espncdn.com/i/teamlogos/soccer/500/6997.png",
};

// Equipos activos por liga en la temporada actual.
// Actualizar aquí cuando un equipo sea eliminado/relegado.
export const EQUIPOS_POR_LIGA: Record<string, string[]> = {
  "Liga MX": [
    // Clausura 2026 — 17 equipos (León descendió a Liga de Expansión)
    "América", "Guadalajara", "Cruz Azul", "Pumas UNAM", "Tigres UANL",
    "Monterrey", "Santos Laguna", "Toluca", "Atlas",
    "Pachuca", "Necaxa", "Querétaro", "FC Juárez", "Mazatlán",
    "Tijuana", "Atlético San Luis", "Puebla",
  ],
  "Champions League": [
    // Octavos de final 2024-25
    "Real Madrid", "Barcelona", "Bayern Munich", "Liverpool",
    "Arsenal", "Inter Milan", "Atlético Madrid", "Borussia Dortmund",
    "Bayer Leverkusen", "Manchester City", "PSG", "Aston Villa",
    "Benfica", "Monaco", "Club Brugge", "Atalanta",
    "Feyenoord", "PSV", "AC Milan", "Juventus",
    "Lille", "Sporting CP", "Celtic", "Brest",
  ],
  "Premier League": [
    // Temporada 2025-26
    "Arsenal", "Liverpool", "Manchester City", "Chelsea", "Aston Villa",
    "Tottenham", "Manchester United", "Newcastle", "West Ham", "Brighton",
    "Wolverhampton", "Fulham", "Bournemouth", "Crystal Palace", "Brentford",
    "Nottingham Forest", "Everton", "Leicester City", "Ipswich Town", "Southampton",
    "Sunderland",
  ],
  "La Liga": [
    // Temporada 2024-25
    "Real Madrid", "Barcelona", "Atlético Madrid", "Athletic Club", "Real Sociedad",
    "Villarreal", "Real Betis", "Sevilla", "Valencia", "Osasuna",
    "Girona", "Celta Vigo", "Rayo Vallecano", "Getafe", "Deportivo Alavés",
    "Mallorca", "Leganés", "Espanyol", "Las Palmas", "Valladolid",
  ],
  "Ligue 1": [
    "PSG", "Olympique de Marseille", "Olympique Lyonnais", "AS Monaco",
    "Lille OSC", "OGC Nice", "RC Lens", "Stade Rennais",
    "Strasbourg", "Nantes", "Montpellier", "Reims",
    "Toulouse FC", "Le Havre", "Auxerre", "Angers",
    "Saint-Étienne",
  ],
  "Brasileirão": [
    // Temporada 2025 (Série A)
    "Flamengo", "Palmeiras", "Atlético Mineiro", "Fluminense",
    "Botafogo", "São Paulo", "Corinthians", "Vasco da Gama",
    "Internacional", "Grêmio", "Santos", "Athletico Paranaense",
    "Cruzeiro", "Bahia", "Red Bull Bragantino", "Mirassol",
    "Coritiba", "Vitória", "Chapecoense", "Sport Recife",
  ],
  "Liga Argentina": [
    "Boca Juniors", "River Plate", "Racing Club", "San Lorenzo",
    "Independiente", "Estudiantes LP", "Vélez Sársfield", "Lanús",
    "Talleres", "Huracán", "Banfield", "Defensa y Justicia",
    "Newell's Old Boys", "Rosario Central", "Argentinos Juniors",
    "Godoy Cruz", "Tigre", "Unión Santa Fe", "Platense", "Colón",
    "Belgrano", "Instituto", "Barracas Central", "Riestra",
    "Atlético Tucumán", "Sarmiento", "Gimnasia LP",
  ],
  "Serie A": [
    // Temporada 2025-26
    "Inter Milan", "AC Milan", "Juventus", "Napoli", "Roma", "Lazio", "Atalanta",
    "Fiorentina", "Torino", "Bologna", "Udinese", "Hellas Verona", "Genoa",
    "Parma", "Lecce", "Cagliari", "Como", "Cremonese", "Pisa", "Sassuolo",
  ],
  "Bundesliga": [
    // Temporada 2025-26
    "Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "RB Leipzig",
    "Eintracht Frankfurt", "Wolfsburg", "Stuttgart", "Borussia Mönchengladbach",
    "Werder Bremen", "SC Freiburg", "Hoffenheim", "Augsburg", "Mainz 05",
    "Union Berlin", "Köln", "St. Pauli", "Heidenheim", "Holstein Kiel",
  ],
  "Copa Libertadores": [
    // Equipos recurrentes — actualizar según fase
    // Brasil
    "Flamengo", "Palmeiras", "Atlético Mineiro", "Fluminense", "Botafogo",
    "São Paulo", "Grêmio", "Internacional", "Athletico Paranaense",
    // Argentina
    "River Plate", "Boca Juniors", "Racing Club", "Estudiantes LP",
    "San Lorenzo", "Independiente", "Talleres", "Argentinos Juniors", "Newell's Old Boys",
    // Uruguay
    "Nacional", "Peñarol",
    // Chile
    "Colo Colo", "Universidad de Chile",
    // Ecuador
    "LDU Quito", "Independiente del Valle",
    // Paraguay
    "Olimpia", "Cerro Porteño", "Libertad",
    // Bolivia
    "Bolívar", "The Strongest",
    // Perú
    "Universitario",
    // Colombia
    "Atlético Nacional", "Millonarios", "Junior",
    // Venezuela
    "Caracas FC", "Deportivo Táchira",
  ],
  "MLS": [
    // Temporada 2026
    "Inter Miami CF", "LA Galaxy", "LAFC", "Seattle Sounders FC", "Portland Timbers",
    "Atlanta United FC", "New York City FC", "Red Bull New York", "Philadelphia Union",
    "FC Cincinnati", "Columbus Crew", "Chicago Fire FC", "D.C. United", "Toronto FC",
    "CF Montréal", "New England Revolution", "Orlando City SC", "Nashville SC",
    "Charlotte FC", "Austin FC", "FC Dallas", "Houston Dynamo FC", "Sporting Kansas City",
    "Colorado Rapids", "Real Salt Lake", "San Jose Earthquakes", "Vancouver Whitecaps",
    "Minnesota United FC", "St. Louis CITY SC", "San Diego FC",
  ],
  "CONCACAF": [
    // Liga MX
    "Guadalajara", "América", "Tigres UANL", "Monterrey", "Cruz Azul", "Pachuca",
    "Pumas UNAM", "León", "Toluca", "Atlas", "Atlético San Luis", "Necaxa",
    // MLS
    "LAFC", "Inter Miami CF", "LA Galaxy", "Columbus Crew", "Seattle Sounders FC",
    "Philadelphia Union", "CF Montréal", "FC Cincinnati", "Portland Timbers",
    "Red Bull New York", "New York City FC", "Nashville SC",
    // Canadá
    "Forge FC", "Pacific FC",
    // Centroamérica
    "Saprissa", "Alajuelense", "Comunicaciones", "Real España", "Olimpia Honduras",
    "Motagua", "Atlético Pantoja",
  ],
  "Amistosos": [
    // Selecciones participantes en amistosos frecuentes
    "México", "Estados Unidos", "Canadá", "Argentina", "Brasil", "Colombia",
    "Uruguay", "Chile", "Perú", "Ecuador", "Venezuela", "Paraguay",
    "España", "Francia", "Alemania", "Portugal", "Inglaterra", "Italia",
    "Países Bajos", "Bélgica", "Croacia", "Suiza", "Polonia", "Dinamarca",
    "Austria", "Suecia", "Noruega", "Turquía", "Japón", "Corea del Sur",
    "Australia", "Marruecos", "Senegal", "Nigeria", "Costa Rica", "Panamá",
    "Honduras", "El Salvador", "Jamaica", "Arabia Saudita", "Irán",
  ],
  "Mundial": [
    // Hosts CONCACAF
    "México", "Estados Unidos", "Canadá",
    // CONMEBOL
    "Argentina", "Brasil", "Uruguay", "Colombia", "Ecuador",
    "Venezuela", "Chile", "Perú", "Paraguay", "Bolivia", "Surinam",
    // UEFA
    "España", "Francia", "Alemania", "Portugal", "Inglaterra", "Italia",
    "Países Bajos", "Bélgica", "Croacia", "Suiza", "Polonia", "Türkiye",
    "Dinamarca", "Austria", "Suecia", "Serbia", "Escocia", "Gales",
    "Rep. Checa", "Rumania", "Grecia", "Hungría", "Ucrania", "Georgia",
    "Eslovaquia", "Eslovenia", "Albania", "Noruega", "Islandia", "Finlandia",
    "Luxemburgo", "Bosnia-Herzegovina",
    // CONCACAF (no hosts)
    "Panamá", "Honduras", "Jamaica", "El Salvador", "Cuba", "Costa Rica",
    // CAF
    "Marruecos", "Senegal", "Nigeria", "Egipto", "Sudáfrica", "Camerún",
    "Costa de Marfil", "Argelia", "Túnez", "R.D. Congo", "Mali", "Guinea", "Ghana",
    // AFC
    "Japón", "Corea del Sur", "Australia", "Arabia Saudita", "Irán",
    "Irak", "Uzbekistán", "Jordania", "Omán", "Indonesia", "Palestina", "Qatar",
    // OFC
    "Nueva Zelanda",
  ],
};

export const LIGAS = Object.keys(EQUIPOS_POR_LIGA);

export const LIGA_ICON: Record<string, string> = {
  "Liga MX":          "🇲🇽",
  "Champions League": "⭐",
  "Premier League":   "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "La Liga":          "🇪🇸",
  "Ligue 1":          "🇫🇷",
  "Brasileirão":      "🇧🇷",
  "Liga Argentina":   "🇦🇷",
  "Serie A":           "🇮🇹",
  "Bundesliga":        "🇩🇪",
  "Copa Libertadores": "🏆",
  "MLS":        "🇺🇸",
  "CONCACAF":   "🌎",
  "Amistosos":  "🌐",
  "Mundial":          "🌍",
  "Mixta":            "⚽",
};

export function getLogoUrl(equipo: string): string {
  if (!equipo) return "";
  // 1. Exacto
  if (LOGOS[equipo]) return LOGOS[equipo];
  // 2. Case-insensitive exacto
  const lower = equipo.toLowerCase();
  for (const [key, url] of Object.entries(LOGOS)) {
    if (key.toLowerCase() === lower) return url;
  }
  // 3. Partial match (uno contiene al otro, normalizado)
  const norm = (s: string) =>
    s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").trim();
  const ne = norm(equipo);
  for (const [key, url] of Object.entries(LOGOS)) {
    const nk = norm(key);
    if (nk.includes(ne) || ne.includes(nk)) return url;
  }
  return "";
}

// Mantener compatibilidad async
export async function getLogoUrlAsync(equipo: string): Promise<string> {
  return getLogoUrl(equipo);
}
