export const MUNDIAL_FECHAS = {
  inicio: "2026-06-11T00:00:00-05:00",
  final:  "2026-07-19T00:00:00-05:00",
};

export type Sede = {
  ciudad: string;
  pais: "México" | "USA" | "Canadá";
  estadio: string;
  capacidad: number;
  emoji: string;
  nota?: string;
};

export const SEDES: Sede[] = [
  // México
  { ciudad: "Ciudad de México", pais: "México", estadio: "Estadio Azteca",      capacidad: 87500, emoji: "🇲🇽", nota: "Semifinal" },
  { ciudad: "Guadalajara",      pais: "México", estadio: "Estadio Akron",        capacidad: 46000, emoji: "🇲🇽" },
  { ciudad: "Monterrey",        pais: "México", estadio: "Estadio BBVA",          capacidad: 51000, emoji: "🇲🇽" },
  // USA
  { ciudad: "Nueva York / NJ",  pais: "USA",    estadio: "MetLife Stadium",       capacidad: 82500, emoji: "🇺🇸", nota: "FINAL 🏆" },
  { ciudad: "Los Ángeles",      pais: "USA",    estadio: "SoFi Stadium",           capacidad: 70000, emoji: "🇺🇸" },
  { ciudad: "Dallas",           pais: "USA",    estadio: "AT&T Stadium",           capacidad: 80000, emoji: "🇺🇸" },
  { ciudad: "San Francisco",    pais: "USA",    estadio: "Levi's Stadium",         capacidad: 68500, emoji: "🇺🇸" },
  { ciudad: "Atlanta",          pais: "USA",    estadio: "Mercedes-Benz Stadium",  capacidad: 71000, emoji: "🇺🇸" },
  { ciudad: "Seattle",          pais: "USA",    estadio: "Lumen Field",            capacidad: 68000, emoji: "🇺🇸" },
  { ciudad: "Houston",          pais: "USA",    estadio: "NRG Stadium",            capacidad: 70000, emoji: "🇺🇸" },
  { ciudad: "Filadelfia",       pais: "USA",    estadio: "Lincoln Financial Field", capacidad: 69000, emoji: "🇺🇸" },
  { ciudad: "Kansas City",      pais: "USA",    estadio: "Arrowhead Stadium",      capacidad: 76000, emoji: "🇺🇸" },
  { ciudad: "Miami",            pais: "USA",    estadio: "Hard Rock Stadium",      capacidad: 65000, emoji: "🇺🇸" },
  { ciudad: "Boston",           pais: "USA",    estadio: "Gillette Stadium",       capacidad: 65000, emoji: "🇺🇸" },
  // Canadá
  { ciudad: "Toronto",          pais: "Canadá", estadio: "BMO Field",             capacidad: 45000, emoji: "🇨🇦" },
  { ciudad: "Vancouver",        pais: "Canadá", estadio: "BC Place",              capacidad: 54000, emoji: "🇨🇦" },
];

export type Jugador = {
  nombre: string;
  posicion: string;
  club: string;
  edad?: number;
  dorsal?: number;
};

export type EquipoDestacado = {
  slug: string;
  pais: string;
  bandera: string;
  confederation: string;
  dt: string;
  dtNacionalidad?: string;
  color: string;        // Tailwind bg class — siempre fondo oscuro para que el texto blanco sea visible
  colorHex: string;     // Para gradientes CSS
  rankingFIFA?: number;
  mundiales: number;
  apariciones: number;
  mejorResultado: string;
  titulos: string[];
  jugadores: Jugador[];
  historia: string;
  curiosidad: string;
  esAnfitrion?: boolean;
};

export const EQUIPOS_DESTACADOS: EquipoDestacado[] = [
  {
    slug: "mexico",
    pais: "México",
    bandera: "🇲🇽",
    confederation: "CONCACAF",
    dt: "Javier Aguirre",
    dtNacionalidad: "Mexicano",
    color: "bg-green-800",
    colorHex: "#166534",
    rankingFIFA: 15,
    mundiales: 0,
    apariciones: 17,
    mejorResultado: "Cuartos de final (1970, 1986)",
    titulos: [],
    jugadores: [
      { nombre: "Guillermo Ochoa",   posicion: "Portero",       club: "Salernitana",       edad: 39, dorsal: 1  },
      { nombre: "Johan Vásquez",     posicion: "Defensa Central",club: "Genoa",            edad: 26, dorsal: 3  },
      { nombre: "Edson Álvarez",     posicion: "Mediocampista",  club: "West Ham",          edad: 27, dorsal: 6  },
      { nombre: "Santi Giménez",     posicion: "Delantero",      club: "AC Milan",          edad: 24, dorsal: 9  },
      { nombre: "Hirving Lozano",    posicion: "Extremo Der.",   club: "PSV",               edad: 30, dorsal: 22 },
      { nombre: "Julián Quiñones",   posicion: "Extremo Izq.",   club: "Club América",      edad: 27, dorsal: 11 },
      { nombre: "Orbelin Pineda",    posicion: "Mediocampista",  club: "AEK Atenas",        edad: 28, dorsal: 8  },
      { nombre: "Luis Romo",         posicion: "Mediocampista",  club: "Cruz Azul",         edad: 29, dorsal: 16 },
      { nombre: "Kevin Álvarez",     posicion: "Lateral Der.",   club: "Club América",      edad: 25, dorsal: 2  },
    ],
    historia: "La Selección Mexicana lleva 17 participaciones en Copas del Mundo, más que cualquier otra selección de la CONCACAF. Su apodo 'El Tri' viene de los tres colores de su bandera. En 1970 y 1986 llegó a cuartos de final como local, pero jamás ha ido más allá. En 2026 juega de nuevo en casa, con el Estadio Azteca como escenario — el único estadio del mundo en albergar tres mundiales.",
    curiosidad: "El Azteca será el único estadio en haber albergado 3 Mundiales: 1970, 1986 y 2026.",
    esAnfitrion: true,
  },
  {
    slug: "argentina",
    pais: "Argentina",
    bandera: "🇦🇷",
    confederation: "CONMEBOL",
    dt: "Lionel Scaloni",
    dtNacionalidad: "Argentino",
    color: "bg-sky-700",
    colorHex: "#0369a1",
    rankingFIFA: 1,
    mundiales: 3,
    apariciones: 19,
    mejorResultado: "Campeón (1978, 1986, 2022)",
    titulos: ["Argentina 1978", "México 1986", "Qatar 2022"],
    jugadores: [
      { nombre: "Emiliano Martínez", posicion: "Portero",        club: "Aston Villa",       edad: 32, dorsal: 23 },
      { nombre: "Nahuel Molina",     posicion: "Lateral Der.",    club: "Atlético Madrid",   edad: 26, dorsal: 26 },
      { nombre: "Cristian Romero",   posicion: "Defensa Central", club: "Tottenham",         edad: 26, dorsal: 13 },
      { nombre: "Lisandro Martínez", posicion: "Defensa Central", club: "Man. United",       edad: 27, dorsal: 25 },
      { nombre: "Rodrigo De Paul",   posicion: "Mediocampista",   club: "Atlético Madrid",   edad: 30, dorsal: 7  },
      { nombre: "Enzo Fernández",    posicion: "Mediocampista",   club: "Chelsea",           edad: 24, dorsal: 24 },
      { nombre: "Lionel Messi",      posicion: "Delantero",       club: "Inter Miami",       edad: 38, dorsal: 10 },
      { nombre: "Julián Álvarez",    posicion: "Delantero",       club: "Atlético Madrid",   edad: 25, dorsal: 9  },
      { nombre: "Lautaro Martínez",  posicion: "Delantero",       club: "Inter Milán",       edad: 27, dorsal: 22 },
    ],
    historia: "Argentina es una de las grandes potencias del fútbol mundial. Tricampeones del mundo, su historia incluye a Diego Maradona como máxima leyenda y a Lionel Messi, quien cerró su leyenda ganando el Mundial de Qatar 2022. Con Scaloni en el banquillo, el equipo ha construido una identidad colectiva que va más allá de cualquier figura individual.",
    curiosidad: "Lionel Messi, a sus 38 años, podría disputar su último Mundial. Busca el bicampeonato que nadie esperaba.",
  },
  {
    slug: "brasil",
    pais: "Brasil",
    bandera: "🇧🇷",
    confederation: "CONMEBOL",
    dt: "Dorival Júnior",
    dtNacionalidad: "Brasileño",
    color: "bg-yellow-600",
    colorHex: "#d97706",
    rankingFIFA: 4,
    mundiales: 5,
    apariciones: 22,
    mejorResultado: "Campeón (1958, 1962, 1970, 1994, 2002)",
    titulos: ["Suecia 1958", "Chile 1962", "México 1970", "USA 1994", "Japón/Corea 2002"],
    jugadores: [
      { nombre: "Alisson Becker",   posicion: "Portero",        club: "Liverpool",         edad: 32, dorsal: 1  },
      { nombre: "Danilo",           posicion: "Lateral Der.",    club: "Juventus",          edad: 33, dorsal: 2  },
      { nombre: "Marquinhos",       posicion: "Defensa Central", club: "PSG",               edad: 30, dorsal: 4  },
      { nombre: "Casemiro",         posicion: "Mediocampista",   club: "Man. United",       edad: 34, dorsal: 5  },
      { nombre: "Bruno Guimarães",  posicion: "Mediocampista",   club: "Newcastle",         edad: 27, dorsal: 8  },
      { nombre: "Vinicius Jr.",     posicion: "Extremo Izq.",    club: "Real Madrid",       edad: 25, dorsal: 7  },
      { nombre: "Rodrygo",          posicion: "Extremo Der.",    club: "Real Madrid",       edad: 24, dorsal: 11 },
      { nombre: "Richarlison",      posicion: "Delantero",       club: "Tottenham",         edad: 28, dorsal: 9  },
      { nombre: "Endrick",          posicion: "Delantero",       club: "Real Madrid",       edad: 19, dorsal: 22 },
    ],
    historia: "La Canarinha es el único equipo en haber participado en todos los Mundiales de la historia (22 de 22). Con 5 títulos son los máximos campeones del planeta. Desde 2002 no levantan la copa, su mayor sequía histórica, lo que genera una presión enorme en cada torneo.",
    curiosidad: "Brasil es el único país que ha jugado TODOS los Mundiales de la historia — los 22.",
  },
  {
    slug: "usa",
    pais: "USA",
    bandera: "🇺🇸",
    confederation: "CONCACAF",
    dt: "Mauricio Pochettino",
    dtNacionalidad: "Argentino",
    color: "bg-blue-800",
    colorHex: "#1e40af",
    rankingFIFA: 11,
    mundiales: 0,
    apariciones: 11,
    mejorResultado: "Tercer lugar (1930)",
    titulos: [],
    jugadores: [
      { nombre: "Matt Turner",        posicion: "Portero",        club: "Nottingham Forest", edad: 30, dorsal: 1  },
      { nombre: "Sergino Dest",       posicion: "Lateral Der.",   club: "PSV",               edad: 24, dorsal: 2  },
      { nombre: "Miles Robinson",     posicion: "Defensa Central",club: "FC Cincinnati",     edad: 28, dorsal: 4  },
      { nombre: "Tyler Adams",        posicion: "Mediocampista",  club: "Bournemouth",       edad: 26, dorsal: 4  },
      { nombre: "Weston McKennie",    posicion: "Mediocampista",  club: "Juventus",          edad: 27, dorsal: 8  },
      { nombre: "Christian Pulisic",  posicion: "Mediocampista",  club: "AC Milan",          edad: 27, dorsal: 10 },
      { nombre: "Gio Reyna",          posicion: "Mediocampista",  club: "Dortmund",          edad: 23, dorsal: 7  },
      { nombre: "Folarin Balogun",    posicion: "Delantero",      club: "Monaco",            edad: 24, dorsal: 9  },
      { nombre: "Timothy Weah",       posicion: "Extremo",        club: "Juventus",          edad: 25, dorsal: 21 },
    ],
    historia: "La USMNT llegó a la semifinal del Mundial de 1930 como sorpresa. En los últimos años ha construido una generación dorada de jugadores europeos (Pulisic, Reyna, Adams, McKennie) con el potencial de ir muy lejos. Con Pochettino al frente y la presión de ser local, 2026 puede ser su gran momento.",
    curiosidad: "La generación 2026 es la más talentosa en la historia de USA — casi todos juegan en Europa.",
    esAnfitrion: true,
  },
  {
    slug: "francia",
    pais: "Francia",
    bandera: "🇫🇷",
    confederation: "UEFA",
    dt: "Didier Deschamps",
    dtNacionalidad: "Francés",
    color: "bg-blue-900",
    colorHex: "#1e3a8a",
    rankingFIFA: 2,
    mundiales: 2,
    apariciones: 16,
    mejorResultado: "Campeón (1998, 2018)",
    titulos: ["Francia 1998", "Rusia 2018"],
    jugadores: [
      { nombre: "Mike Maignan",       posicion: "Portero",        club: "AC Milan",          edad: 29, dorsal: 16 },
      { nombre: "Jules Koundé",       posicion: "Lateral Der.",   club: "FC Barcelona",      edad: 26, dorsal: 5  },
      { nombre: "Dayot Upamecano",    posicion: "Defensa Central",club: "Bayern München",    edad: 26, dorsal: 4  },
      { nombre: "William Saliba",     posicion: "Defensa Central",club: "Arsenal",           edad: 24, dorsal: 17 },
      { nombre: "Aurelien Tchouameni",posicion: "Mediocampista",  club: "Real Madrid",       edad: 25, dorsal: 8  },
      { nombre: "N'Golo Kanté",       posicion: "Mediocampista",  club: "Al-Ittihad",        edad: 35, dorsal: 13 },
      { nombre: "Antoine Griezmann",  posicion: "Mediocampista",  club: "Atlético Madrid",   edad: 35, dorsal: 7  },
      { nombre: "Kylian Mbappé",      posicion: "Delantero",      club: "Real Madrid",       edad: 27, dorsal: 10 },
      { nombre: "Ousmane Dembélé",    posicion: "Extremo",        club: "PSG",               edad: 29, dorsal: 11 },
    ],
    historia: "Les Bleus son bicampeones del mundo. Su talento es multicultural y refrescante: desde Platini y Zidane hasta Mbappé. En Qatar 2022 llegaron a la final con una actuación memorable de Mbappé, quien marcó 8 goles incluyendo un hat-trick en la final. Deschamps busca su tercera estrella como DT.",
    curiosidad: "Deschamps es el único francés en ganar el Mundial tanto como jugador (1998) como entrenador (2018).",
  },
  {
    slug: "espana",
    pais: "España",
    bandera: "🇪🇸",
    confederation: "UEFA",
    dt: "Luis de la Fuente",
    dtNacionalidad: "Español",
    color: "bg-red-700",
    colorHex: "#b91c1c",
    rankingFIFA: 3,
    mundiales: 1,
    apariciones: 16,
    mejorResultado: "Campeón (2010)",
    titulos: ["Sudáfrica 2010"],
    jugadores: [
      { nombre: "Unai Simón",       posicion: "Portero",         club: "Athletic Bilbao",   edad: 27, dorsal: 1  },
      { nombre: "Dani Carvajal",    posicion: "Lateral Der.",    club: "Real Madrid",        edad: 32, dorsal: 2  },
      { nombre: "Aymeric Laporte",  posicion: "Defensa Central", club: "Al-Nassr",          edad: 31, dorsal: 14 },
      { nombre: "Robin Le Normand", posicion: "Defensa Central", club: "Atlético Madrid",   edad: 28, dorsal: 24 },
      { nombre: "Rodri",            posicion: "Pivote",          club: "Manchester City",   edad: 29, dorsal: 16 },
      { nombre: "Pedri",            posicion: "Mediocampista",   club: "FC Barcelona",      edad: 23, dorsal: 8  },
      { nombre: "Fabián Ruiz",      posicion: "Mediocampista",   club: "PSG",               edad: 28, dorsal: 7  },
      { nombre: "Lamine Yamal",     posicion: "Extremo Der.",    club: "FC Barcelona",      edad: 18, dorsal: 19 },
      { nombre: "Álvaro Morata",    posicion: "Delantero",       club: "AC Milan",          edad: 33, dorsal: 9  },
    ],
    historia: "La Roja dominó el fútbol mundial entre 2008 y 2012 ganando dos Eurocopas y un Mundial con el revolucionario 'tiki-taka'. Después de años de reconstrucción, encontraron la siguiente gran generación con Gavi, Pedri y Lamine Yamal, ganando la Eurocopa 2024. Son nuevamente candidatos serios.",
    curiosidad: "Lamine Yamal cumplió 17 años el día antes de la final de la Euro 2024 — y la ganó siendo figura.",
  },
  {
    slug: "alemania",
    pais: "Alemania",
    bandera: "🇩🇪",
    confederation: "UEFA",
    dt: "Julian Nagelsmann",
    dtNacionalidad: "Alemán",
    color: "bg-zinc-800",
    colorHex: "#27272a",
    rankingFIFA: 12,
    mundiales: 4,
    apariciones: 20,
    mejorResultado: "Campeón (1954, 1974, 1990, 2014)",
    titulos: ["Suiza 1954", "Alemania Occ. 1974", "Italia 1990", "Brasil 2014"],
    jugadores: [
      { nombre: "Manuel Neuer",     posicion: "Portero",         club: "Bayern München",    edad: 40, dorsal: 1  },
      { nombre: "Joshua Kimmich",   posicion: "Lateral Der.",    club: "Bayern München",    edad: 31, dorsal: 6  },
      { nombre: "Antonio Rüdiger",  posicion: "Defensa Central", club: "Real Madrid",       edad: 33, dorsal: 2  },
      { nombre: "Jonathan Tah",     posicion: "Defensa Central", club: "Bayer Leverkusen",  edad: 29, dorsal: 4  },
      { nombre: "Toni Kroos",       posicion: "Mediocampista",   club: "Real Madrid",       edad: 35, dorsal: 8  },
      { nombre: "Jamal Musiala",    posicion: "Mediocampista",   club: "Bayern München",    edad: 22, dorsal: 10 },
      { nombre: "Florian Wirtz",    posicion: "Mediocampista",   club: "Bayer Leverkusen",  edad: 23, dorsal: 17 },
      { nombre: "Leroy Sané",       posicion: "Extremo",         club: "Bayern München",    edad: 30, dorsal: 19 },
      { nombre: "Kai Havertz",      posicion: "Delantero",       club: "Arsenal",           edad: 26, dorsal: 7  },
    ],
    historia: "Die Mannschaft es la selección europea más laureada del mundo con 4 títulos. Conocidos por su disciplina táctica y su capacidad de reinventarse, sufrieron la peor eliminación de su historia al caer en grupos en 2018 y 2022. Nagelsmann apuesta por la juventud de Musiala y Wirtz para recuperar la gloria.",
    curiosidad: "Alemania es la única selección en haber llegado a la semifinal en 4 Mundiales consecutivos (1982–1990).",
  },
  {
    slug: "inglaterra",
    pais: "Inglaterra",
    bandera: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    confederation: "UEFA",
    dt: "Lee Carsley",
    dtNacionalidad: "Irlandés/Inglés",
    color: "bg-slate-700",    // ← oscuro para que el texto blanco sea visible
    colorHex: "#334155",
    rankingFIFA: 5,
    mundiales: 1,
    apariciones: 16,
    mejorResultado: "Campeón (1966)",
    titulos: ["Inglaterra 1966"],
    jugadores: [
      { nombre: "Jordan Pickford",   posicion: "Portero",         club: "Everton",           edad: 32, dorsal: 1  },
      { nombre: "Trent A-Arnold",    posicion: "Lateral Der.",    club: "Real Madrid",       edad: 27, dorsal: 2  },
      { nombre: "John Stones",       posicion: "Defensa Central", club: "Manchester City",   edad: 32, dorsal: 5  },
      { nombre: "Marc Guéhi",        posicion: "Defensa Central", club: "Crystal Palace",    edad: 24, dorsal: 6  },
      { nombre: "Jude Bellingham",   posicion: "Mediocampista",   club: "Real Madrid",       edad: 23, dorsal: 10 },
      { nombre: "Phil Foden",        posicion: "Mediocampista",   club: "Manchester City",   edad: 26, dorsal: 7  },
      { nombre: "Declan Rice",       posicion: "Pivote",          club: "Arsenal",           edad: 27, dorsal: 4  },
      { nombre: "Bukayo Saka",       posicion: "Extremo Der.",    club: "Arsenal",           edad: 24, dorsal: 7  },
      { nombre: "Harry Kane",        posicion: "Delantero",       club: "Bayern München",    edad: 33, dorsal: 9  },
    ],
    historia: "Los Three Lions ganaron su único Mundial en 1966, en casa, con el legendario Geoff Hurst marcando hat-trick en la final. Desde entonces, 60 años de sueños rotos — eliminados en penales más veces que ninguna otra selección. La generación actual de Bellingham, Kane y Saka es posiblemente la más talentosa desde 1966.",
    curiosidad: "Inglaterra ha sido eliminada en penales 7 veces en Mundiales y Eurocopas — más que cualquier otro país.",
  },
  {
    slug: "marruecos",
    pais: "Marruecos",
    bandera: "🇲🇦",
    confederation: "CAF",
    dt: "Walid Regragui",
    dtNacionalidad: "Marroquí-Francés",
    color: "bg-red-900",
    colorHex: "#7f1d1d",
    rankingFIFA: 14,
    mundiales: 0,
    apariciones: 7,
    mejorResultado: "Semifinal (2022)",
    titulos: [],
    jugadores: [
      { nombre: "Yassine Bounou",     posicion: "Portero",         club: "Al-Hilal",          edad: 33, dorsal: 1  },
      { nombre: "Achraf Hakimi",      posicion: "Lateral Der.",    club: "PSG",               edad: 27, dorsal: 2  },
      { nombre: "Nayef Aguerd",       posicion: "Defensa Central", club: "West Ham",          edad: 28, dorsal: 5  },
      { nombre: "Romain Saïss",       posicion: "Defensa Central", club: "Besiktas",          edad: 34, dorsal: 13 },
      { nombre: "Sofyan Amrabat",     posicion: "Pivote",          club: "Fiorentina",        edad: 28, dorsal: 4  },
      { nombre: "Azzedine Ounahi",    posicion: "Mediocampista",   club: "Marseille",         edad: 24, dorsal: 8  },
      { nombre: "Hakim Ziyech",       posicion: "Extremo",         club: "Galatasaray",       edad: 33, dorsal: 7  },
      { nombre: "Youssef En-Nesyri",  posicion: "Delantero",       club: "Fenerbahçe",        edad: 27, dorsal: 9  },
      { nombre: "Soufiane Rahimi",    posicion: "Extremo",         club: "Al-Ain",            edad: 27, dorsal: 11 },
    ],
    historia: "Los Leones del Atlas escribieron historia en Qatar 2022 al convertirse en la primera selección africana en llegar a las semifinales de un Mundial. Eliminaron a España y Portugal en el camino. Su mezcla de jugadores formados en Europa con profundo sentido de identidad marroquí los hace un equipo fascinante.",
    curiosidad: "En Qatar 2022 fueron la primera selección africana en llegar a semis — y lo hicieron sin recibir un solo gol en tiempo regular.",
  },
  {
    slug: "japon",
    pais: "Japón",
    bandera: "🇯🇵",
    confederation: "AFC",
    dt: "Hajime Moriyasu",
    dtNacionalidad: "Japonés",
    color: "bg-blue-700",
    colorHex: "#1d4ed8",
    rankingFIFA: 17,
    mundiales: 0,
    apariciones: 8,
    mejorResultado: "Ronda de 16 (2002, 2010, 2018, 2022)",
    titulos: [],
    jugadores: [
      { nombre: "Shuichi Gonda",    posicion: "Portero",         club: "Shimizu S-Pulse",   edad: 35, dorsal: 12 },
      { nombre: "Hiroki Sakai",     posicion: "Lateral Der.",    club: "Urawa Reds",         edad: 34, dorsal: 5  },
      { nombre: "Ko Itakura",       posicion: "Defensa Central", club: "Borussia Mönchengladbach", edad: 27, dorsal: 3 },
      { nombre: "Wataru Endo",      posicion: "Pivote",          club: "Liverpool",          edad: 31, dorsal: 17 },
      { nombre: "Daichi Kamada",    posicion: "Mediocampista",   club: "Crystal Palace",    edad: 28, dorsal: 14 },
      { nombre: "Kaoru Mitoma",     posicion: "Extremo Izq.",    club: "Brighton",           edad: 27, dorsal: 10 },
      { nombre: "Ritsu Doan",       posicion: "Extremo Der.",    club: "SC Freiburg",        edad: 26, dorsal: 9  },
      { nombre: "Takumi Minamino",  posicion: "Mediocampista",   club: "Monaco",             edad: 29, dorsal: 10 },
      { nombre: "Ayase Ueda",       posicion: "Delantero",       club: "Feyenoord",          edad: 26, dorsal: 16 },
    ],
    historia: "La Samurai Blue se ha convertido en la potencia asiática del fútbol. Eliminaron a Alemania y España en Qatar 2022, quedando subcampeones del grupo de la muerte. Sus jugadores están cada vez más presentes en las grandes ligas europeas, y Japón sigue levantando el nivel competitivo de la AFC.",
    curiosidad: "En Qatar 2022 remontaron 0-1 a Alemania y 0-1 a España en el mismo grupo — impresionante.",
  },
{
  slug: "canada",
  pais: "Canadá",
  bandera: "🇨🇦",
  confederation: "CONCACAF",
  dt: "Jesse Marsch",
  dtNacionalidad: "Estados Unidos",
  color: "bg-red-700",
  colorHex: "#b91c1c",
  rankingFIFA: 31,
  mundiales: 0,
  apariciones: 3,
  mejorResultado: "Fase de grupos (1986, 2022)",
  titulos: [],
  jugadores: [
    { nombre: "Alphonso Davies", posicion: "Lateral izquierdo", club: "Real Madrid", edad: 25, dorsal: 19 },
    { nombre: "Jonathan David", posicion: "Delantero", club: "Juventus", edad: 26, dorsal: 20 },
    { nombre: "Stephen Eustáquio", posicion: "Mediocampista", club: "Porto", edad: 29, dorsal: 7 },
    { nombre: "Cyle Larin", posicion: "Delantero", club: "Mallorca", edad: 31, dorsal: 17 },
    { nombre: "Tajon Buchanan", posicion: "Extremo", club: "Inter de Milán", edad: 27, dorsal: 11 },
    { nombre: "Maxime Crépeau", posicion: "Portero", club: "Portland Timbers", edad: 32, dorsal: 16 }
  ],
  historia: "Canadá disputó su primer Mundial en México 1986 y regresó al máximo escenario en Qatar 2022 tras 36 años de ausencia. Como coanfitrión del Mundial 2026, vive su mejor generación histórica con figuras de élite europea.",
  curiosidad: "Es la primera vez que Canadá organiza una Copa del Mundo masculina, compartiendo la sede con Estados Unidos y México.",
  esAnfitrion: true
},
{
  slug: "costa-rica",
  pais: "Costa Rica",
  bandera: "🇨🇷",
  confederation: "CONCACAF",
  dt: "Miguel Herrera",
  dtNacionalidad: "México",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 54,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Cuartos de final (Brasil 2014)",
  titulos: [],
  jugadores: [
    { nombre: "Keylor Navas", posicion: "Portero", club: "Newell's Old Boys", edad: 39, dorsal: 1 },
    { nombre: "Joel Campbell", posicion: "Delantero", club: "Saprissa", edad: 33, dorsal: 12 },
    { nombre: "Francisco Calvo", posicion: "Defensor", club: "Konyaspor", edad: 33, dorsal: 15 },
    { nombre: "Manfred Ugalde", posicion: "Delantero", club: "Spartak Moscú", edad: 24, dorsal: 9 },
    { nombre: "Celso Borges", posicion: "Mediocampista", club: "Alajuelense", edad: 37, dorsal: 5 }
  ],
  historia: "Costa Rica debutó en Italia 1990 y firmó la mayor gesta de su historia en Brasil 2014, llegando a cuartos de final como líder de un grupo con Uruguay, Italia e Inglaterra. Es la selección centroamericana con más Mundiales disputados.",
  curiosidad: "En 2014 Keylor Navas fue elegido el portero del torneo tras eliminar a Grecia en penales y caer ante Países Bajos solo desde los doce pasos."
},
{
  slug: "honduras",
  pais: "Honduras",
  bandera: "🇭🇳",
  confederation: "CONCACAF",
  dt: "Reinaldo Rueda",
  dtNacionalidad: "Colombia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 78,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos (1982, 2010, 2014)",
  titulos: [],
  jugadores: [
    { nombre: "Romell Quioto", posicion: "Delantero", club: "CF Montréal", edad: 34, dorsal: 9 },
    { nombre: "Anthony Lozano", posicion: "Delantero", club: "Cádiz", edad: 32, dorsal: 13 },
    { nombre: "Andy Najar", posicion: "Lateral", club: "Inter Miami", edad: 32, dorsal: 17 },
    { nombre: "Luis Palma", posicion: "Extremo", club: "Celtic", edad: 26, dorsal: 7 },
    { nombre: "Edrick Menjívar", posicion: "Portero", club: "Olimpia", edad: 33, dorsal: 1 }
  ],
  historia: "La Bicolor disputó su primer Mundial en España 1982 con un debut histórico empatando ante el anfitrión. Volvió a Sudáfrica 2010 y Brasil 2014, y vuelve al máximo escenario tras más de una década de ausencia.",
  curiosidad: "Honduras es famosa por la 'Guerra del Fútbol' de 1969 contra El Salvador, conflicto desatado tras un partido eliminatorio."
},
{
  slug: "jamaica",
  pais: "Jamaica",
  bandera: "🇯🇲",
  confederation: "CONCACAF",
  dt: "Steve McClaren",
  dtNacionalidad: "Inglaterra",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 65,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Fase de grupos (Francia 1998)",
  titulos: [],
  jugadores: [
    { nombre: "Leon Bailey", posicion: "Extremo", club: "Aston Villa", edad: 28, dorsal: 7 },
    { nombre: "Michail Antonio", posicion: "Delantero", club: "West Ham", edad: 36, dorsal: 9 },
    { nombre: "Demarai Gray", posicion: "Extremo", club: "Al-Ettifaq", edad: 30, dorsal: 11 },
    { nombre: "Bobby Decordova-Reid", posicion: "Mediocampista", club: "Leicester", edad: 33, dorsal: 14 },
    { nombre: "Andre Blake", posicion: "Portero", club: "Philadelphia Union", edad: 35, dorsal: 1 }
  ],
  historia: "Los Reggae Boyz debutaron en Francia 1998, donde lograron una histórica victoria 2-1 sobre Japón. Vuelven al Mundial tras 28 años con una generación nutrida por jugadores nacidos o criados en Inglaterra.",
  curiosidad: "La canción 'Rise Up' de Jimmy Cliff se convirtió en el himno extraoficial de los Reggae Boyz durante su aventura en Francia 1998."
},
{
  slug: "panama",
  pais: "Panamá",
  bandera: "🇵🇦",
  confederation: "CONCACAF",
  dt: "Thomas Christiansen",
  dtNacionalidad: "Dinamarca",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 41,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Fase de grupos (Rusia 2018)",
  titulos: [],
  jugadores: [
    { nombre: "Adalberto Carrasquilla", posicion: "Mediocampista", club: "Pumas UNAM", edad: 27, dorsal: 20 },
    { nombre: "Aníbal Godoy", posicion: "Mediocampista", club: "San Jose Earthquakes", edad: 36, dorsal: 20 },
    { nombre: "Michael Amir Murillo", posicion: "Lateral", club: "Marsella", edad: 30, dorsal: 13 },
    { nombre: "José Fajardo", posicion: "Delantero", club: "Tauro FC", edad: 31, dorsal: 9 },
    { nombre: "Orlando Mosquera", posicion: "Portero", club: "Universitario", edad: 31, dorsal: 1 }
  ],
  historia: "Panamá clasificó por primera vez a un Mundial en Rusia 2018, día que fue declarado feriado nacional. La Marea Roja vuelve al escenario mundial siendo una de las selecciones más competitivas de Concacaf.",
  curiosidad: "El gol de Felipe Baloy ante Inglaterra en Rusia 2018 fue el primer gol mundialista de Panamá en toda su historia."
},
{
  slug: "el-salvador",
  pais: "El Salvador",
  bandera: "🇸🇻",
  confederation: "CONCACAF",
  dt: "Hernán Darío Gómez",
  dtNacionalidad: "Colombia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 92,
  mundiales: 0,
  apariciones: 3,
  mejorResultado: "Fase de grupos (1970, 1982)",
  titulos: [],
  jugadores: [
    { nombre: "Alex Roldán", posicion: "Lateral", club: "Seattle Sounders", edad: 30, dorsal: 16 },
    { nombre: "Enrico Hernández", posicion: "Mediocampista", club: "FAS", edad: 25, dorsal: 8 },
    { nombre: "Eriq Zavaleta", posicion: "Defensor", club: "Toronto FC", edad: 33, dorsal: 4 },
    { nombre: "Mario González", posicion: "Portero", club: "Alianza", edad: 33, dorsal: 1 },
    { nombre: "Joshua Pérez", posicion: "Delantero", club: "Águila", edad: 28, dorsal: 9 }
  ],
  historia: "La Selecta participó en México 1970 y España 1982. En este último torneo encajó la mayor goleada en la historia de los Mundiales: 10-1 ante Hungría. Regresa al máximo escenario tras más de cuatro décadas.",
  curiosidad: "El partido entre El Salvador y Hungría en España 1982 sigue ostentando el récord de la mayor goleada en un Mundial."
},
{
  slug: "guatemala",
  pais: "Guatemala",
  bandera: "🇬🇹",
  confederation: "CONCACAF",
  dt: "Luis Fernando Tena",
  dtNacionalidad: "México",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 100,
  mundiales: 0,
  apariciones: 1,
  mejorResultado: "Fase de grupos (2026)",
  titulos: [],
  jugadores: [
    { nombre: "Rubio Rubín", posicion: "Delantero", club: "Real Salt Lake", edad: 30, dorsal: 11 },
    { nombre: "Aaron Herrera", posicion: "Lateral", club: "DC United", edad: 28, dorsal: 22 },
    { nombre: "Nicholas Hagen", posicion: "Portero", club: "Columbus Crew", edad: 29, dorsal: 1 },
    { nombre: "Óscar Santis", posicion: "Extremo", club: "Antigua GFC", edad: 29, dorsal: 7 },
    { nombre: "Stheven Robles", posicion: "Mediocampista", club: "Municipal", edad: 28, dorsal: 8 }
  ],
  historia: "Guatemala debuta en una Copa del Mundo en 2026 tras décadas intentando la clasificación. La Azul y Blanco vivirá una experiencia inédita en el primer Mundial con 48 selecciones.",
  curiosidad: "Guatemala es uno de los países con mayor cantidad de aficionados al fútbol per cápita en Centroamérica, pese a no haber jugado un Mundial hasta ahora."
},
{
  slug: "colombia",
  pais: "Colombia",
  bandera: "🇨🇴",
  confederation: "CONMEBOL",
  dt: "Néstor Lorenzo",
  dtNacionalidad: "Argentina",
  color: "bg-yellow-700",
  colorHex: "#a16207",
  rankingFIFA: 12,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Cuartos de final (1990 sub-versión, 2014)",
  titulos: [],
  jugadores: [
    { nombre: "James Rodríguez", posicion: "Mediocampista", club: "Club León", edad: 34, dorsal: 10 },
    { nombre: "Luis Díaz", posicion: "Extremo", club: "Bayern Múnich", edad: 29, dorsal: 7 },
    { nombre: "Jhon Durán", posicion: "Delantero", club: "Al-Nassr", edad: 22, dorsal: 9 },
    { nombre: "Dávinson Sánchez", posicion: "Defensor", club: "Galatasaray", edad: 29, dorsal: 23 },
    { nombre: "Richard Ríos", posicion: "Mediocampista", club: "Benfica", edad: 25, dorsal: 16 },
    { nombre: "Camilo Vargas", posicion: "Portero", club: "Atlas", edad: 36, dorsal: 1 }
  ],
  historia: "Colombia vivió su época dorada con Valderrama, Asprilla y Rincón en los años 90, y volvió a brillar en Brasil 2014 con James Rodríguez como goleador del torneo. Subcampeona de la Copa América 2024.",
  curiosidad: "James Rodríguez ganó el Balón de Oro al mejor gol de Brasil 2014 con su volea de pecho ante Uruguay en octavos de final."
},
{
  slug: "uruguay",
  pais: "Uruguay",
  bandera: "🇺🇾",
  confederation: "CONMEBOL",
  dt: "Marcelo Bielsa",
  dtNacionalidad: "Argentina",
  color: "bg-sky-800",
  colorHex: "#075985",
  rankingFIFA: 11,
  mundiales: 2,
  apariciones: 15,
  mejorResultado: "Campeón (Uruguay 1930, Brasil 1950)",
  titulos: ["Uruguay 1930", "Brasil 1950"],
  jugadores: [
    { nombre: "Federico Valverde", posicion: "Mediocampista", club: "Real Madrid", edad: 27, dorsal: 15 },
    { nombre: "Darwin Núñez", posicion: "Delantero", club: "Al-Hilal", edad: 26, dorsal: 9 },
    { nombre: "Ronald Araújo", posicion: "Defensor", club: "Barcelona", edad: 27, dorsal: 4 },
    { nombre: "Manuel Ugarte", posicion: "Mediocampista", club: "Manchester United", edad: 25, dorsal: 5 },
    { nombre: "Maxi Araújo", posicion: "Extremo", club: "Sporting", edad: 25, dorsal: 11 },
    { nombre: "Sergio Rochet", posicion: "Portero", club: "Internacional", edad: 33, dorsal: 1 }
  ],
  historia: "La Celeste fue campeona del primer Mundial en 1930 en casa y volvió a ganarlo en 1950 con el legendario Maracanazo ante Brasil. Es una de las selecciones más laureadas del fútbol sudamericano.",
  curiosidad: "Las cuatro estrellas en el escudo de Uruguay representan no solo sus dos Mundiales, sino también sus dos medallas de oro olímpicas de 1924 y 1928, reconocidas por la FIFA."
},
{
  slug: "ecuador",
  pais: "Ecuador",
  bandera: "🇪🇨",
  confederation: "CONMEBOL",
  dt: "Sebastián Beccacece",
  dtNacionalidad: "Argentina",
  color: "bg-yellow-700",
  colorHex: "#a16207",
  rankingFIFA: 23,
  mundiales: 0,
  apariciones: 5,
  mejorResultado: "Octavos de final (Alemania 2006)",
  titulos: [],
  jugadores: [
    { nombre: "Moisés Caicedo", posicion: "Mediocampista", club: "Chelsea", edad: 24, dorsal: 23 },
    { nombre: "Piero Hincapié", posicion: "Defensor", club: "Arsenal", edad: 24, dorsal: 3 },
    { nombre: "Pervis Estupiñán", posicion: "Lateral", club: "AC Milan", edad: 28, dorsal: 7 },
    { nombre: "Enner Valencia", posicion: "Delantero", club: "Internacional", edad: 36, dorsal: 13 },
    { nombre: "Kendry Páez", posicion: "Mediocampista", club: "Chelsea", edad: 19, dorsal: 20 },
    { nombre: "Hernán Galíndez", posicion: "Portero", club: "Rosario Central", edad: 39, dorsal: 1 }
  ],
  historia: "Ecuador debutó en Corea-Japón 2002 y alcanzó los octavos de final en Alemania 2006. La Tri es hoy una de las selecciones jóvenes más prometedoras del continente.",
  curiosidad: "Antonio Valencia, capitán histórico, comenzó su carrera vendiendo periódicos en Lago Agrio antes de llegar al Manchester United."
},
{
  slug: "venezuela",
  pais: "Venezuela",
  bandera: "🇻🇪",
  confederation: "CONMEBOL",
  dt: "Fernando Batista",
  dtNacionalidad: "Argentina",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 47,
  mundiales: 0,
  apariciones: 1,
  mejorResultado: "Fase de grupos (2026)",
  titulos: [],
  jugadores: [
    { nombre: "Salomón Rondón", posicion: "Delantero", club: "Pachuca", edad: 36, dorsal: 23 },
    { nombre: "Yeferson Soteldo", posicion: "Extremo", club: "Fluminense", edad: 28, dorsal: 11 },
    { nombre: "Jhon Murillo", posicion: "Extremo", club: "Tondela", edad: 30, dorsal: 17 },
    { nombre: "Tomás Rincón", posicion: "Mediocampista", club: "Santos", edad: 38, dorsal: 8 },
    { nombre: "Rafael Romo", posicion: "Portero", club: "UCV", edad: 35, dorsal: 1 }
  ],
  historia: "La Vinotinto cumple el sueño histórico de clasificar a su primer Mundial en 2026, rompiendo la barrera de ser la única selección sudamericana sin participaciones. Fue cuarta en la Copa América 2011.",
  curiosidad: "Venezuela fue considerada históricamente país de béisbol, pero el éxito de la Vinotinto cambió radicalmente la cultura deportiva del país en el siglo XXI."
},
{
  slug: "bolivia",
  pais: "Bolivia",
  bandera: "🇧🇴",
  confederation: "CONMEBOL",
  dt: "Óscar Villegas",
  dtNacionalidad: "Bolivia",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 84,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos (1930, 1950, 1994)",
  titulos: [],
  jugadores: [
    { nombre: "Marcelo Moreno Martins", posicion: "Delantero", club: "Independiente Petrolero", edad: 38, dorsal: 11 },
    { nombre: "Miguel Terceros", posicion: "Mediocampista", club: "Santos", edad: 21, dorsal: 10 },
    { nombre: "Diego Medina", posicion: "Defensor", club: "Always Ready", edad: 22, dorsal: 4 },
    { nombre: "Henry Vaca", posicion: "Mediocampista", club: "Bolívar", edad: 27, dorsal: 8 },
    { nombre: "Carlos Lampe", posicion: "Portero", club: "Always Ready", edad: 38, dorsal: 1 }
  ],
  historia: "Bolivia participó en los primeros Mundiales de 1930 y 1950, y volvió a Estados Unidos 1994 tras 44 años de ausencia. Ahora regresa al máximo escenario tras 32 años, beneficiada por la altitud de La Paz.",
  curiosidad: "El Estadio Hernando Siles de La Paz, a 3,637 metros sobre el nivel del mar, es considerado el más alto del fútbol sudamericano y un fortín de la Verde."
},
{
  slug: "paraguay",
  pais: "Paraguay",
  bandera: "🇵🇾",
  confederation: "CONMEBOL",
  dt: "Gustavo Alfaro",
  dtNacionalidad: "Argentina",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 38,
  mundiales: 0,
  apariciones: 9,
  mejorResultado: "Cuartos de final (Sudáfrica 2010)",
  titulos: [],
  jugadores: [
    { nombre: "Miguel Almirón", posicion: "Mediocampista", club: "Atlanta United", edad: 31, dorsal: 10 },
    { nombre: "Antonio Sanabria", posicion: "Delantero", club: "Cremonese", edad: 29, dorsal: 19 },
    { nombre: "Gustavo Gómez", posicion: "Defensor", club: "Palmeiras", edad: 32, dorsal: 4 },
    { nombre: "Damián Bobadilla", posicion: "Mediocampista", club: "São Paulo", edad: 23, dorsal: 5 },
    { nombre: "Julio Enciso", posicion: "Extremo", club: "Ipswich Town", edad: 22, dorsal: 11 },
    { nombre: "Roberto Fernández", posicion: "Portero", club: "Olimpia", edad: 31, dorsal: 1 }
  ],
  historia: "Paraguay vivió su mejor actuación en Sudáfrica 2010 al llegar a cuartos de final, donde cayó por la mínima ante España, el campeón de la edición. La Albirroja regresa tras 16 años de ausencia.",
  curiosidad: "José Luis Chilavert, su portero histórico, marcó ocho goles oficiales con la selección, una cifra inusual para un guardameta."
},
{
  slug: "chile",
  pais: "Chile",
  bandera: "🇨🇱",
  confederation: "CONMEBOL",
  dt: "Ricardo Gareca",
  dtNacionalidad: "Argentina",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 56,
  mundiales: 0,
  apariciones: 10,
  mejorResultado: "Tercer lugar (Chile 1962)",
  titulos: [],
  jugadores: [
    { nombre: "Alexis Sánchez", posicion: "Delantero", club: "Udinese", edad: 37, dorsal: 7 },
    { nombre: "Ben Brereton Díaz", posicion: "Delantero", club: "Sheffield United", edad: 27, dorsal: 22 },
    { nombre: "Arturo Vidal", posicion: "Mediocampista", club: "Colo-Colo", edad: 39, dorsal: 8 },
    { nombre: "Gabriel Suazo", posicion: "Lateral", club: "Sevilla", edad: 28, dorsal: 3 },
    { nombre: "Darío Osorio", posicion: "Extremo", club: "Midtjylland", edad: 22, dorsal: 20 },
    { nombre: "Claudio Bravo", posicion: "Portero", club: "Colo-Colo", edad: 43, dorsal: 1 }
  ],
  historia: "Chile fue tercero en su Mundial de 1962. La Roja vivió una época dorada entre 2014 y 2017, ganando dos Copas América consecutivas, pero ahora regresa al Mundial tras tres ausencias.",
  curiosidad: "La 'Generación Dorada' chilena de Sánchez, Vidal y Bravo conquistó la Copa América 2015 y 2016 venciendo a Argentina en ambas finales."
},
{
  slug: "peru",
  pais: "Perú",
  bandera: "🇵🇪",
  confederation: "CONMEBOL",
  dt: "Óscar Ibáñez",
  dtNacionalidad: "Argentina-Perú",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 49,
  mundiales: 0,
  apariciones: 6,
  mejorResultado: "Cuartos de final (1970, 1978)",
  titulos: [],
  jugadores: [
    { nombre: "Paolo Guerrero", posicion: "Delantero", club: "Alianza Lima", edad: 42, dorsal: 9 },
    { nombre: "Gianluca Lapadula", posicion: "Delantero", club: "Cagliari", edad: 36, dorsal: 17 },
    { nombre: "Renato Tapia", posicion: "Mediocampista", club: "Leganés", edad: 30, dorsal: 13 },
    { nombre: "Luis Advíncula", posicion: "Lateral", club: "Boca Juniors", edad: 36, dorsal: 17 },
    { nombre: "Pedro Gallese", posicion: "Portero", club: "Orlando City", edad: 36, dorsal: 1 }
  ],
  historia: "Perú vivió su época dorada en los 70 con Cubillas, Chumpitaz y Sotil, llegando a cuartos en 1970 y 1978. Regresó al Mundial en Rusia 2018 tras 36 años y vuelve nuevamente al escenario mundial.",
  curiosidad: "Teófilo Cubillas es uno de los pocos jugadores que ha marcado cinco o más goles en dos ediciones distintas de una Copa del Mundo."
},
{
  slug: "portugal",
  pais: "Portugal",
  bandera: "🇵🇹",
  confederation: "UEFA",
  dt: "Roberto Martínez",
  dtNacionalidad: "España",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 6,
  mundiales: 0,
  apariciones: 9,
  mejorResultado: "Tercer lugar (Inglaterra 1966)",
  titulos: [],
  jugadores: [
    { nombre: "Cristiano Ronaldo", posicion: "Delantero", club: "Al-Nassr", edad: 41, dorsal: 7 },
    { nombre: "Bruno Fernandes", posicion: "Mediocampista", club: "Manchester United", edad: 31, dorsal: 8 },
    { nombre: "Bernardo Silva", posicion: "Mediocampista", club: "Manchester City", edad: 31, dorsal: 10 },
    { nombre: "Rafael Leão", posicion: "Extremo", club: "AC Milan", edad: 26, dorsal: 17 },
    { nombre: "Rúben Dias", posicion: "Defensor", club: "Manchester City", edad: 29, dorsal: 4 },
    { nombre: "Diogo Costa", posicion: "Portero", club: "Porto", edad: 26, dorsal: 22 }
  ],
  historia: "Portugal fue tercero en Inglaterra 1966 con Eusébio como figura. Campeona de la Eurocopa 2016 y de la UEFA Nations League 2019, vive el final de la era Cristiano Ronaldo.",
  curiosidad: "Cristiano Ronaldo es el único jugador en haber marcado en cinco Copas del Mundo distintas y máximo goleador histórico de selecciones."
},
{
  slug: "paises-bajos",
  pais: "Países Bajos",
  bandera: "🇳🇱",
  confederation: "UEFA",
  dt: "Ronald Koeman",
  dtNacionalidad: "Países Bajos",
  color: "bg-orange-700",
  colorHex: "#c2410c",
  rankingFIFA: 7,
  mundiales: 0,
  apariciones: 12,
  mejorResultado: "Subcampeón (1974, 1978, 2010)",
  titulos: [],
  jugadores: [
    { nombre: "Virgil van Dijk", posicion: "Defensor", club: "Liverpool", edad: 34, dorsal: 4 },
    { nombre: "Frenkie de Jong", posicion: "Mediocampista", club: "Barcelona", edad: 29, dorsal: 21 },
    { nombre: "Memphis Depay", posicion: "Delantero", club: "Corinthians", edad: 32, dorsal: 10 },
    { nombre: "Cody Gakpo", posicion: "Extremo", club: "Liverpool", edad: 27, dorsal: 11 },
    { nombre: "Xavi Simons", posicion: "Mediocampista", club: "RB Leipzig", edad: 23, dorsal: 7 },
    { nombre: "Bart Verbruggen", posicion: "Portero", club: "Brighton", edad: 23, dorsal: 1 }
  ],
  historia: "La Naranja Mecánica revolucionó el fútbol con el 'fútbol total' de Cruyff en los 70, pero perdió tres finales mundialistas (1974, 1978, 2010). Es la mejor selección sin haber ganado un Mundial.",
  curiosidad: "Johan Cruyff inventó la jugada conocida como 'la croqueta de Cruyff' en el Mundial de 1974 ante Suecia, considerada una de las mejores fintas de la historia."
},
{
  slug: "italia",
  pais: "Italia",
  bandera: "🇮🇹",
  confederation: "UEFA",
  dt: "Gennaro Gattuso",
  dtNacionalidad: "Italia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 9,
  mundiales: 4,
  apariciones: 19,
  mejorResultado: "Campeón (1934, 1938, 1982, 2006)",
  titulos: ["Italia 1934", "Francia 1938", "España 1982", "Alemania 2006"],
  jugadores: [
    { nombre: "Gianluigi Donnarumma", posicion: "Portero", club: "Manchester City", edad: 27, dorsal: 21 },
    { nombre: "Federico Chiesa", posicion: "Extremo", club: "Liverpool", edad: 28, dorsal: 14 },
    { nombre: "Nicolò Barella", posicion: "Mediocampista", club: "Inter de Milán", edad: 29, dorsal: 18 },
    { nombre: "Alessandro Bastoni", posicion: "Defensor", club: "Inter de Milán", edad: 27, dorsal: 23 },
    { nombre: "Mateo Retegui", posicion: "Delantero", club: "Al-Qadsiah", edad: 27, dorsal: 9 },
    { nombre: "Sandro Tonali", posicion: "Mediocampista", club: "Newcastle", edad: 26, dorsal: 8 }
  ],
  historia: "La Azzurra es tetracampeona del mundo y una de las selecciones más laureadas. Tras ausentarse de los Mundiales de 2018 y 2022, regresa al máximo escenario tras 12 años de ausencia.",
  curiosidad: "Italia es la única selección que ha ganado dos Mundiales consecutivos en formato directo (1934 y 1938) además de Brasil."
},
{
  slug: "belgica",
  pais: "Bélgica",
  bandera: "🇧🇪",
  confederation: "UEFA",
  dt: "Rudi García",
  dtNacionalidad: "Francia",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 8,
  mundiales: 0,
  apariciones: 15,
  mejorResultado: "Tercer lugar (Rusia 2018)",
  titulos: [],
  jugadores: [
    { nombre: "Kevin De Bruyne", posicion: "Mediocampista", club: "Napoli", edad: 34, dorsal: 7 },
    { nombre: "Romelu Lukaku", posicion: "Delantero", club: "Napoli", edad: 33, dorsal: 9 },
    { nombre: "Jérémy Doku", posicion: "Extremo", club: "Manchester City", edad: 24, dorsal: 11 },
    { nombre: "Youri Tielemans", posicion: "Mediocampista", club: "Aston Villa", edad: 28, dorsal: 8 },
    { nombre: "Thibaut Courtois", posicion: "Portero", club: "Real Madrid", edad: 33, dorsal: 1 },
    { nombre: "Wout Faes", posicion: "Defensor", club: "Leicester", edad: 28, dorsal: 4 }
  ],
  historia: "Los Diablos Rojos vivieron una generación dorada con Hazard, De Bruyne y Lukaku que fue tercera en Rusia 2018. Bélgica es uno de los grandes 'casi' del fútbol mundial.",
  curiosidad: "Bélgica llegó a ser número 1 del ranking FIFA durante varios años consecutivos sin haber ganado nunca un título mayor."
},
{
  slug: "croacia",
  pais: "Croacia",
  bandera: "🇭🇷",
  confederation: "UEFA",
  dt: "Zlatko Dalić",
  dtNacionalidad: "Croacia",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 10,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Subcampeón (Rusia 2018)",
  titulos: [],
  jugadores: [
    { nombre: "Luka Modrić", posicion: "Mediocampista", club: "AC Milan", edad: 40, dorsal: 10 },
    { nombre: "Mateo Kovačić", posicion: "Mediocampista", club: "Manchester City", edad: 32, dorsal: 8 },
    { nombre: "Joško Gvardiol", posicion: "Defensor", club: "Manchester City", edad: 24, dorsal: 20 },
    { nombre: "Andrej Kramarić", posicion: "Delantero", club: "Hoffenheim", edad: 34, dorsal: 9 },
    { nombre: "Dominik Livaković", posicion: "Portero", club: "Fenerbahçe", edad: 31, dorsal: 1 },
    { nombre: "Luka Sučić", posicion: "Mediocampista", club: "Real Sociedad", edad: 23, dorsal: 14 }
  ],
  historia: "Croacia se independizó en 1991 y debutó en Francia 1998 logrando el tercer lugar con Davor Šuker como goleador. Fue subcampeona en Rusia 2018 y tercera en Qatar 2022, todo con Luka Modrić como capitán.",
  curiosidad: "Croacia es el país más pequeño en haber llegado a una final de la Copa del Mundo en el siglo XXI, con apenas 4 millones de habitantes."
},
{
  slug: "suiza",
  pais: "Suiza",
  bandera: "🇨🇭",
  confederation: "UEFA",
  dt: "Murat Yakin",
  dtNacionalidad: "Suiza",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 19,
  mundiales: 0,
  apariciones: 13,
  mejorResultado: "Cuartos de final (1934, 1938, 1954)",
  titulos: [],
  jugadores: [
    { nombre: "Granit Xhaka", posicion: "Mediocampista", club: "Bayer Leverkusen", edad: 33, dorsal: 10 },
    { nombre: "Manuel Akanji", posicion: "Defensor", club: "Manchester City", edad: 30, dorsal: 5 },
    { nombre: "Breel Embolo", posicion: "Delantero", club: "Mónaco", edad: 28, dorsal: 7 },
    { nombre: "Xherdan Shaqiri", posicion: "Extremo", club: "Basel", edad: 34, dorsal: 23 },
    { nombre: "Yann Sommer", posicion: "Portero", club: "Inter de Milán", edad: 37, dorsal: 1 },
    { nombre: "Dan Ndoye", posicion: "Extremo", club: "Bologna", edad: 25, dorsal: 9 }
  ],
  historia: "Suiza es habitual en las Copas del Mundo y suele caer en octavos de final. Su mejor resultado data de la era previa a 1958, cuando fue cuartofinalista en tres ocasiones.",
  curiosidad: "Suiza fue anfitriona del Mundial de 1954, recordado como el del 'Milagro de Berna' donde Alemania Federal venció a Hungría."
},
{
  slug: "austria",
  pais: "Austria",
  bandera: "🇦🇹",
  confederation: "UEFA",
  dt: "Ralf Rangnick",
  dtNacionalidad: "Alemania",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 22,
  mundiales: 0,
  apariciones: 8,
  mejorResultado: "Tercer lugar (Italia 1934 — semifinal en Uruguay 1954)",
  titulos: [],
  jugadores: [
    { nombre: "David Alaba", posicion: "Defensor", club: "Real Madrid", edad: 34, dorsal: 8 },
    { nombre: "Marcel Sabitzer", posicion: "Mediocampista", club: "Borussia Dortmund", edad: 31, dorsal: 7 },
    { nombre: "Marko Arnautović", posicion: "Delantero", club: "Inter de Milán", edad: 37, dorsal: 9 },
    { nombre: "Konrad Laimer", posicion: "Mediocampista", club: "Bayern Múnich", edad: 28, dorsal: 6 },
    { nombre: "Christoph Baumgartner", posicion: "Mediocampista", club: "RB Leipzig", edad: 26, dorsal: 19 }
  ],
  historia: "Austria vivió su época dorada en los años 30 con el 'Wunderteam' y fue tercera en 1954. Tras décadas en segunda fila europea, vuelve al Mundial de la mano de Ralf Rangnick.",
  curiosidad: "El Wunderteam austriaco de los años 30 dirigido por Hugo Meisl es considerado uno de los primeros grandes equipos tácticos modernos del fútbol."
},
{
  slug: "turquia",
  pais: "Turquía",
  bandera: "🇹🇷",
  confederation: "UEFA",
  dt: "Vincenzo Montella",
  dtNacionalidad: "Italia",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 27,
  mundiales: 0,
  apariciones: 3,
  mejorResultado: "Tercer lugar (Corea-Japón 2002)",
  titulos: [],
  jugadores: [
    { nombre: "Hakan Çalhanoğlu", posicion: "Mediocampista", club: "Inter de Milán", edad: 32, dorsal: 10 },
    { nombre: "Arda Güler", posicion: "Mediocampista", club: "Real Madrid", edad: 21, dorsal: 15 },
    { nombre: "Kenan Yıldız", posicion: "Extremo", club: "Juventus", edad: 21, dorsal: 11 },
    { nombre: "Merih Demiral", posicion: "Defensor", club: "Al-Ahli", edad: 28, dorsal: 3 },
    { nombre: "Mert Günok", posicion: "Portero", club: "Beşiktaş", edad: 37, dorsal: 1 }
  ],
  historia: "Turquía sorprendió al mundo en Corea-Japón 2002 al terminar en tercer lugar con Hakan Şükür y Rüştü Reçber como figuras. Vuelve a un Mundial tras 24 años con una nueva generación brillante.",
  curiosidad: "Hakan Şükür marcó el gol más rápido en la historia de los Mundiales: tan solo 10.8 segundos contra Corea del Sur en 2002."
},
{
  slug: "polonia",
  pais: "Polonia",
  bandera: "🇵🇱",
  confederation: "UEFA",
  dt: "Jan Urban",
  dtNacionalidad: "Polonia",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 34,
  mundiales: 0,
  apariciones: 10,
  mejorResultado: "Tercer lugar (1974, 1982)",
  titulos: [],
  jugadores: [
    { nombre: "Robert Lewandowski", posicion: "Delantero", club: "Barcelona", edad: 37, dorsal: 9 },
    { nombre: "Piotr Zieliński", posicion: "Mediocampista", club: "Inter de Milán", edad: 31, dorsal: 20 },
    { nombre: "Nicola Zalewski", posicion: "Lateral", club: "Inter de Milán", edad: 24, dorsal: 16 },
    { nombre: "Wojciech Szczęsny", posicion: "Portero", club: "Barcelona", edad: 36, dorsal: 1 },
    { nombre: "Jakub Kiwior", posicion: "Defensor", club: "Arsenal", edad: 26, dorsal: 5 }
  ],
  historia: "Polonia tuvo su época dorada en los años 70 y 80 con dos terceros puestos. Hoy gira en torno a Robert Lewandowski, uno de los mejores delanteros de su generación.",
  curiosidad: "Grzegorz Lato fue el máximo goleador del Mundial de 1974 con siete tantos, llevando a Polonia al tercer lugar en Alemania."
},
{
  slug: "serbia",
  pais: "Serbia",
  bandera: "🇷🇸",
  confederation: "UEFA",
  dt: "Veljko Paunović",
  dtNacionalidad: "Serbia",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 33,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Dušan Vlahović", posicion: "Delantero", club: "Juventus", edad: 26, dorsal: 9 },
    { nombre: "Aleksandar Mitrović", posicion: "Delantero", club: "Al-Hilal", edad: 32, dorsal: 18 },
    { nombre: "Sergej Milinković-Savić", posicion: "Mediocampista", club: "Al-Hilal", edad: 31, dorsal: 20 },
    { nombre: "Dušan Tadić", posicion: "Mediocampista", club: "Fenerbahçe", edad: 37, dorsal: 10 },
    { nombre: "Predrag Rajković", posicion: "Portero", club: "Espanyol", edad: 30, dorsal: 1 }
  ],
  historia: "Serbia, heredera de la histórica Yugoslavia, ha disputado cuatro Mundiales sin lograr pasar de la fase de grupos. Posee una de las generaciones ofensivas más potentes de Europa.",
  curiosidad: "La antigua Yugoslavia fue cuarta en dos Mundiales (1930 y 1962), y aunque Serbia hereda esa federación, FIFA solo le reconoce los registros desde 2006."
},
{
  slug: "escocia",
  pais: "Escocia",
  bandera: "🏴",
  confederation: "UEFA",
  dt: "Steve Clarke",
  dtNacionalidad: "Escocia",
  color: "bg-blue-900",
  colorHex: "#1e3a8a",
  rankingFIFA: 40,
  mundiales: 0,
  apariciones: 9,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Andrew Robertson", posicion: "Lateral", club: "Liverpool", edad: 32, dorsal: 3 },
    { nombre: "Scott McTominay", posicion: "Mediocampista", club: "Napoli", edad: 29, dorsal: 4 },
    { nombre: "John McGinn", posicion: "Mediocampista", club: "Aston Villa", edad: 31, dorsal: 7 },
    { nombre: "Che Adams", posicion: "Delantero", club: "Torino", edad: 30, dorsal: 9 },
    { nombre: "Angus Gunn", posicion: "Portero", club: "Norwich", edad: 30, dorsal: 1 }
  ],
  historia: "Escocia, una de las naciones fundadoras del fútbol, tiene una larga tradición sin haber pasado nunca de la fase de grupos. Regresa al Mundial tras 28 años de ausencia desde Francia 1998.",
  curiosidad: "El primer partido internacional de fútbol de la historia fue entre Escocia e Inglaterra en 1872 y terminó 0-0."
},
{
  slug: "rumania",
  pais: "Rumanía",
  bandera: "🇷🇴",
  confederation: "UEFA",
  dt: "Mircea Lucescu",
  dtNacionalidad: "Rumanía",
  color: "bg-yellow-700",
  colorHex: "#a16207",
  rankingFIFA: 45,
  mundiales: 0,
  apariciones: 8,
  mejorResultado: "Cuartos de final (Estados Unidos 1994)",
  titulos: [],
  jugadores: [
    { nombre: "Ianis Hagi", posicion: "Mediocampista", club: "Alanyaspor", edad: 27, dorsal: 10 },
    { nombre: "Răzvan Marin", posicion: "Mediocampista", club: "Cagliari", edad: 30, dorsal: 7 },
    { nombre: "Nicolae Stanciu", posicion: "Mediocampista", club: "Damac FC", edad: 33, dorsal: 8 },
    { nombre: "Radu Drăgușin", posicion: "Defensor", club: "Tottenham", edad: 24, dorsal: 4 },
    { nombre: "Florin Niță", posicion: "Portero", club: "Gaziantep", edad: 38, dorsal: 1 }
  ],
  historia: "Rumanía vivió su mejor Mundial en Estados Unidos 1994 con Gheorghe Hagi como estrella, llegando a cuartos. Vuelve al máximo escenario tras 28 años de ausencia.",
  curiosidad: "Gheorghe Hagi, apodado 'El Maradona de los Cárpatos', es considerado el mejor futbolista rumano de la historia y padre de Ianis Hagi."
},
{
  slug: "dinamarca",
  pais: "Dinamarca",
  bandera: "🇩🇰",
  confederation: "UEFA",
  dt: "Brian Riemer",
  dtNacionalidad: "Dinamarca",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 21,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Cuartos de final (Francia 1998)",
  titulos: [],
  jugadores: [
    { nombre: "Christian Eriksen", posicion: "Mediocampista", club: "Wolfsburgo", edad: 34, dorsal: 10 },
    { nombre: "Pierre-Emile Højbjerg", posicion: "Mediocampista", club: "Marsella", edad: 31, dorsal: 23 },
    { nombre: "Rasmus Højlund", posicion: "Delantero", club: "Napoli", edad: 23, dorsal: 9 },
    { nombre: "Andreas Christensen", posicion: "Defensor", club: "Barcelona", edad: 30, dorsal: 6 },
    { nombre: "Kasper Schmeichel", posicion: "Portero", club: "Celtic", edad: 39, dorsal: 1 }
  ],
  historia: "Dinamarca ganó la Eurocopa 1992 tras ser repescada por la exclusión de Yugoslavia. En los Mundiales, su tope fue cuartos en Francia 1998 con los hermanos Laudrup.",
  curiosidad: "Dinamarca fue la última campeona en obtener el título de la Eurocopa sin haber clasificado deportivamente al torneo."
},
{
  slug: "noruega",
  pais: "Noruega",
  bandera: "🇳🇴",
  confederation: "UEFA",
  dt: "Ståle Solbakken",
  dtNacionalidad: "Noruega",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 32,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Octavos de final (Francia 1998)",
  titulos: [],
  jugadores: [
    { nombre: "Erling Haaland", posicion: "Delantero", club: "Manchester City", edad: 26, dorsal: 9 },
    { nombre: "Martin Ødegaard", posicion: "Mediocampista", club: "Arsenal", edad: 27, dorsal: 10 },
    { nombre: "Alexander Sørloth", posicion: "Delantero", club: "Atlético de Madrid", edad: 30, dorsal: 11 },
    { nombre: "Antonio Nusa", posicion: "Extremo", club: "RB Leipzig", edad: 20, dorsal: 7 },
    { nombre: "Ørjan Nyland", posicion: "Portero", club: "Sevilla", edad: 35, dorsal: 1 }
  ],
  historia: "Noruega vivió su última participación mundialista en Francia 1998, donde llegó a octavos tras vencer a Brasil en fase de grupos. Vuelve al máximo escenario tras 28 años con Haaland y Ødegaard.",
  curiosidad: "Noruega es la única selección europea que mantiene un saldo positivo contra Brasil en partidos internacionales oficiales."
},
{
  slug: "ucrania",
  pais: "Ucrania",
  bandera: "🇺🇦",
  confederation: "UEFA",
  dt: "Serhiy Rebrov",
  dtNacionalidad: "Ucrania",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 25,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Cuartos de final (Alemania 2006)",
  titulos: [],
  jugadores: [
    { nombre: "Mykhailo Mudryk", posicion: "Extremo", club: "Chelsea", edad: 25, dorsal: 10 },
    { nombre: "Oleksandr Zinchenko", posicion: "Lateral", club: "Arsenal", edad: 29, dorsal: 17 },
    { nombre: "Artem Dovbyk", posicion: "Delantero", club: "Roma", edad: 28, dorsal: 9 },
    { nombre: "Ruslan Malinovskyi", posicion: "Mediocampista", club: "Genoa", edad: 32, dorsal: 8 },
    { nombre: "Anatoliy Trubin", posicion: "Portero", club: "Benfica", edad: 24, dorsal: 1 }
  ],
  historia: "Ucrania debutó como nación independiente en Alemania 2006 con Andriy Shevchenko a la cabeza y llegó hasta cuartos de final. Vuelve al Mundial tras dos décadas y en medio de un conflicto bélico.",
  curiosidad: "Andriy Shevchenko, ganador del Balón de Oro 2004, es el máximo goleador histórico de la selección ucraniana con 48 goles."
},
{
  slug: "eslovenia",
  pais: "Eslovenia",
  bandera: "🇸🇮",
  confederation: "UEFA",
  dt: "Matjaž Kek",
  dtNacionalidad: "Eslovenia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 53,
  mundiales: 0,
  apariciones: 3,
  mejorResultado: "Fase de grupos (2002, 2010)",
  titulos: [],
  jugadores: [
    { nombre: "Jan Oblak", posicion: "Portero", club: "Atlético de Madrid", edad: 33, dorsal: 1 },
    { nombre: "Benjamin Šeško", posicion: "Delantero", club: "Manchester United", edad: 23, dorsal: 9 },
    { nombre: "Jaka Bijol", posicion: "Defensor", club: "Leeds", edad: 27, dorsal: 5 },
    { nombre: "Adam Gnezda Čerin", posicion: "Mediocampista", club: "Panathinaikos", edad: 27, dorsal: 8 },
    { nombre: "Andraž Šporar", posicion: "Delantero", club: "Panathinaikos", edad: 32, dorsal: 17 }
  ],
  historia: "Eslovenia debutó en Corea-Japón 2002 y volvió a Sudáfrica 2010. Es uno de los países más pequeños de Europa que ha sabido competir con regularidad en torneos importantes.",
  curiosidad: "Con apenas 2 millones de habitantes, Eslovenia es uno de los países menos poblados que ha clasificado a múltiples Copas del Mundo."
},
{
  slug: "hungria",
  pais: "Hungría",
  bandera: "🇭🇺",
  confederation: "UEFA",
  dt: "Marco Rossi",
  dtNacionalidad: "Italia",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 36,
  mundiales: 0,
  apariciones: 10,
  mejorResultado: "Subcampeón (1938, 1954)",
  titulos: [],
  jugadores: [
    { nombre: "Dominik Szoboszlai", posicion: "Mediocampista", club: "Liverpool", edad: 26, dorsal: 10 },
    { nombre: "Willi Orbán", posicion: "Defensor", club: "RB Leipzig", edad: 33, dorsal: 5 },
    { nombre: "Roland Sallai", posicion: "Extremo", club: "Galatasaray", edad: 29, dorsal: 9 },
    { nombre: "András Schäfer", posicion: "Mediocampista", club: "Union Berlin", edad: 27, dorsal: 8 },
    { nombre: "Péter Gulácsi", posicion: "Portero", club: "RB Leipzig", edad: 36, dorsal: 12 }
  ],
  historia: "Hungría tuvo el legendario 'Equipo de Oro' de los años 50 con Puskás, Kocsis y Hidegkuti, dos veces subcampeona del mundo. Regresa al Mundial tras 40 años de ausencia desde México 1986.",
  curiosidad: "Ferenc Puskás dio nombre al premio FIFA al gol más bello del año, en honor a uno de los mejores futbolistas de la historia."
},
{
  slug: "grecia",
  pais: "Grecia",
  bandera: "🇬🇷",
  confederation: "UEFA",
  dt: "Iván Jovanović",
  dtNacionalidad: "Serbia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 44,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Octavos de final (Brasil 2014)",
  titulos: [],
  jugadores: [
    { nombre: "Kostas Tsimikas", posicion: "Lateral", club: "Liverpool", edad: 30, dorsal: 21 },
    { nombre: "Vangelis Pavlidis", posicion: "Delantero", club: "Benfica", edad: 27, dorsal: 9 },
    { nombre: "Konstantinos Mavropanos", posicion: "Defensor", club: "West Ham", edad: 28, dorsal: 4 },
    { nombre: "Anastasios Bakasetas", posicion: "Mediocampista", club: "Eyüpspor", edad: 32, dorsal: 10 },
    { nombre: "Odisseas Vlachodimos", posicion: "Portero", club: "Newcastle", edad: 31, dorsal: 1 }
  ],
  historia: "Grecia sorprendió al mundo ganando la Eurocopa 2004 bajo el mando de Otto Rehhagel. En Mundiales su mejor actuación fue Brasil 2014, donde llegó a octavos por primera vez.",
  curiosidad: "La victoria de Grecia en la Eurocopa 2004 está considerada una de las mayores sorpresas en la historia del fútbol moderno."
},
{
  slug: "senegal",
  pais: "Senegal",
  bandera: "🇸🇳",
  confederation: "CAF",
  dt: "Pape Thiaw",
  dtNacionalidad: "Senegal",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 17,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Cuartos de final (Corea-Japón 2002)",
  titulos: [],
  jugadores: [
    { nombre: "Sadio Mané", posicion: "Extremo", club: "Al-Nassr", edad: 33, dorsal: 10 },
    { nombre: "Kalidou Koulibaly", posicion: "Defensor", club: "Al-Hilal", edad: 35, dorsal: 3 },
    { nombre: "Édouard Mendy", posicion: "Portero", club: "Al-Ahli", edad: 33, dorsal: 16 },
    { nombre: "Ismaïla Sarr", posicion: "Extremo", club: "Crystal Palace", edad: 28, dorsal: 18 },
    { nombre: "Nicolas Jackson", posicion: "Delantero", club: "Bayern Múnich", edad: 24, dorsal: 9 },
    { nombre: "Pape Matar Sarr", posicion: "Mediocampista", club: "Tottenham", edad: 23, dorsal: 17 }
  ],
  historia: "Senegal asombró en su debut mundialista en Corea-Japón 2002 al vencer a Francia y llegar a cuartos. Ganaron la Copa Africana de Naciones 2021 y son una de las potencias del continente.",
  curiosidad: "Senegal venció 1-0 a Francia, vigente campeona del mundo, en el partido inaugural del Mundial 2002, considerado una de las mayores sorpresas históricas."
},
{
  slug: "nigeria",
  pais: "Nigeria",
  bandera: "🇳🇬",
  confederation: "CAF",
  dt: "Eric Chelle",
  dtNacionalidad: "Mali",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 42,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Octavos de final (1994, 1998, 2014)",
  titulos: [],
  jugadores: [
    { nombre: "Victor Osimhen", posicion: "Delantero", club: "Galatasaray", edad: 27, dorsal: 9 },
    { nombre: "Ademola Lookman", posicion: "Extremo", club: "Atalanta", edad: 28, dorsal: 11 },
    { nombre: "William Troost-Ekong", posicion: "Defensor", club: "Al-Kholood", edad: 32, dorsal: 5 },
    { nombre: "Wilfred Ndidi", posicion: "Mediocampista", club: "Besiktas", edad: 29, dorsal: 4 },
    { nombre: "Stanley Nwabali", posicion: "Portero", club: "Chippa United", edad: 29, dorsal: 23 }
  ],
  historia: "Las Súper Águilas debutaron en Estados Unidos 1994 sorprendiendo al mundo. Tres veces campeona de África (1980, 1994, 2013), Nigeria es una de las potencias del fútbol africano.",
  curiosidad: "Nigeria ganó el oro olímpico en Atlanta 1996 venciendo a Argentina en la final, siendo la primera selección africana en lograrlo."
},
{
  slug: "egipto",
  pais: "Egipto",
  bandera: "🇪🇬",
  confederation: "CAF",
  dt: "Hossam Hassan",
  dtNacionalidad: "Egipto",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 35,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Mohamed Salah", posicion: "Extremo", club: "Liverpool", edad: 33, dorsal: 10 },
    { nombre: "Omar Marmoush", posicion: "Delantero", club: "Manchester City", edad: 27, dorsal: 9 },
    { nombre: "Mohamed Elneny", posicion: "Mediocampista", club: "Al-Jazira", edad: 33, dorsal: 17 },
    { nombre: "Trezeguet", posicion: "Extremo", club: "Trabzonspor", edad: 31, dorsal: 11 },
    { nombre: "Mohamed El-Shenawy", posicion: "Portero", club: "Al-Ahly", edad: 37, dorsal: 1 }
  ],
  historia: "Egipto fue la primera selección africana en disputar un Mundial, en Italia 1934. Récord absoluto en la Copa Africana de Naciones con 7 títulos, vuelve al Mundial tras la ausencia de 2022.",
  curiosidad: "Mohamed Salah es el máximo goleador histórico de Egipto y dos veces ganador de la Bota de Oro de la Premier League."
},
{
  slug: "camerun",
  pais: "Camerún",
  bandera: "🇨🇲",
  confederation: "CAF",
  dt: "Marc Brys",
  dtNacionalidad: "Bélgica",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 50,
  mundiales: 0,
  apariciones: 9,
  mejorResultado: "Cuartos de final (Italia 1990)",
  titulos: [],
  jugadores: [
    { nombre: "André Onana", posicion: "Portero", club: "Trabzonspor", edad: 29, dorsal: 24 },
    { nombre: "Vincent Aboubakar", posicion: "Delantero", club: "Hatayspor", edad: 33, dorsal: 10 },
    { nombre: "Bryan Mbeumo", posicion: "Extremo", club: "Manchester United", edad: 26, dorsal: 19 },
    { nombre: "Frank Anguissa", posicion: "Mediocampista", club: "Napoli", edad: 30, dorsal: 8 },
    { nombre: "Carlos Baleba", posicion: "Mediocampista", club: "Brighton", edad: 21, dorsal: 6 }
  ],
  historia: "Camerún hizo historia en Italia 1990 al ser la primera selección africana en llegar a cuartos de final, con Roger Milla como leyenda. Es la selección africana con más apariciones mundialistas.",
  curiosidad: "Roger Milla, con sus famosos bailes en el banderín, marcó goles en Italia 1990 con 38 años y en Estados Unidos 1994 con 42, récord histórico."
},
{
  slug: "ghana",
  pais: "Ghana",
  bandera: "🇬🇭",
  confederation: "CAF",
  dt: "Otto Addo",
  dtNacionalidad: "Ghana",
  color: "bg-yellow-700",
  colorHex: "#a16207",
  rankingFIFA: 73,
  mundiales: 0,
  apariciones: 5,
  mejorResultado: "Cuartos de final (Sudáfrica 2010)",
  titulos: [],
  jugadores: [
    { nombre: "Mohammed Kudus", posicion: "Mediocampista", club: "Tottenham", edad: 25, dorsal: 20 },
    { nombre: "Thomas Partey", posicion: "Mediocampista", club: "Villarreal", edad: 32, dorsal: 5 },
    { nombre: "Jordan Ayew", posicion: "Delantero", club: "Leicester", edad: 34, dorsal: 10 },
    { nombre: "Antoine Semenyo", posicion: "Extremo", club: "Bournemouth", edad: 26, dorsal: 11 },
    { nombre: "Lawrence Ati-Zigi", posicion: "Portero", club: "St. Gallen", edad: 29, dorsal: 1 }
  ],
  historia: "Las Estrellas Negras estuvieron a un penal de hacer historia en Sudáfrica 2010, cayendo en cuartos ante Uruguay tras el polémico mano de Suárez. Cuatro veces campeón de África.",
  curiosidad: "El penal fallado por Asamoah Gyan ante Uruguay en 2010 hubiera convertido a Ghana en la primera selección africana en alcanzar las semifinales de un Mundial."
},
{
  slug: "costa-de-marfil",
  pais: "Costa de Marfil",
  bandera: "🇨🇮",
  confederation: "CAF",
  dt: "Emerse Faé",
  dtNacionalidad: "Costa de Marfil",
  color: "bg-orange-700",
  colorHex: "#c2410c",
  rankingFIFA: 39,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Sébastien Haller", posicion: "Delantero", club: "Leganés", edad: 31, dorsal: 12 },
    { nombre: "Franck Kessié", posicion: "Mediocampista", club: "Al-Ahli", edad: 28, dorsal: 19 },
    { nombre: "Simon Adingra", posicion: "Extremo", club: "Sunderland", edad: 23, dorsal: 11 },
    { nombre: "Évan Ndicka", posicion: "Defensor", club: "Roma", edad: 26, dorsal: 4 },
    { nombre: "Yahia Fofana", posicion: "Portero", club: "Angers", edad: 25, dorsal: 16 }
  ],
  historia: "Costa de Marfil vivió la era dorada de Drogba, Touré y Eboué entre 2006 y 2014. Vigente campeona africana al ganar la Copa Africana de Naciones 2023 en casa con una remontada histórica.",
  curiosidad: "En 2005, Didier Drogba pidió a los grupos en guerra deponer las armas tras la clasificación al Mundial 2006, contribuyendo al alto al fuego en Costa de Marfil."
},
{
  slug: "sudafrica",
  pais: "Sudáfrica",
  bandera: "🇿🇦",
  confederation: "CAF",
  dt: "Hugo Broos",
  dtNacionalidad: "Bélgica",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 58,
  mundiales: 0,
  apariciones: 4,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Ronwen Williams", posicion: "Portero", club: "Mamelodi Sundowns", edad: 33, dorsal: 1 },
    { nombre: "Themba Zwane", posicion: "Mediocampista", club: "Mamelodi Sundowns", edad: 36, dorsal: 10 },
    { nombre: "Lyle Foster", posicion: "Delantero", club: "Burnley", edad: 25, dorsal: 11 },
    { nombre: "Percy Tau", posicion: "Extremo", club: "Al-Ahly", edad: 31, dorsal: 22 },
    { nombre: "Teboho Mokoena", posicion: "Mediocampista", club: "Mamelodi Sundowns", edad: 29, dorsal: 8 }
  ],
  historia: "Sudáfrica organizó el primer Mundial en suelo africano en 2010, aunque no logró pasar de la fase de grupos, siendo el único anfitrión eliminado en primera ronda. Vuelve al Mundial tras 16 años.",
  curiosidad: "La vuvuzela, la trompeta característica del Mundial 2010, se convirtió en símbolo del torneo y polémico protagonista por su sonido constante."
},
{
  slug: "argelia",
  pais: "Argelia",
  bandera: "🇩🇿",
  confederation: "CAF",
  dt: "Vladimir Petković",
  dtNacionalidad: "Suiza-Bosnia",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 37,
  mundiales: 0,
  apariciones: 5,
  mejorResultado: "Octavos de final (Brasil 2014)",
  titulos: [],
  jugadores: [
    { nombre: "Riyad Mahrez", posicion: "Extremo", club: "Al-Ahli", edad: 35, dorsal: 7 },
    { nombre: "Ismaël Bennacer", posicion: "Mediocampista", club: "AC Milan", edad: 28, dorsal: 6 },
    { nombre: "Houssem Aouar", posicion: "Mediocampista", club: "Al-Ittihad", edad: 28, dorsal: 8 },
    { nombre: "Aïssa Mandi", posicion: "Defensor", club: "Lille", edad: 34, dorsal: 4 },
    { nombre: "Saïd Benrahma", posicion: "Extremo", club: "Lyon", edad: 30, dorsal: 11 }
  ],
  historia: "Argelia derrotó a Alemania Occidental en su debut mundialista en 1982. Llegó a octavos en Brasil 2014 cayendo en prórroga ante la futura campeona Alemania. Campeona africana 2019.",
  curiosidad: "El llamado 'Desastre de Gijón' de 1982, donde Alemania y Austria pactaron un resultado que eliminó a Argelia, llevó a la FIFA a obligar a jugar simultáneamente la última jornada de grupo."
},
{
  slug: "tunez",
  pais: "Túnez",
  bandera: "🇹🇳",
  confederation: "CAF",
  dt: "Sami Trabelsi",
  dtNacionalidad: "Túnez",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 48,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Hannibal Mejbri", posicion: "Mediocampista", club: "Burnley", edad: 23, dorsal: 6 },
    { nombre: "Wahbi Khazri", posicion: "Delantero", club: "Montpellier", edad: 35, dorsal: 10 },
    { nombre: "Aïssa Laïdouni", posicion: "Mediocampista", club: "Union Berlin", edad: 29, dorsal: 14 },
    { nombre: "Ellyes Skhiri", posicion: "Mediocampista", club: "Eintracht Frankfurt", edad: 31, dorsal: 13 },
    { nombre: "Aymen Dahmen", posicion: "Portero", club: "Kasımpaşa", edad: 28, dorsal: 1 }
  ],
  historia: "Túnez fue la primera selección africana en ganar un partido en un Mundial, derrotando a México 3-1 en Argentina 1978. Las Águilas de Cartago vuelven al máximo escenario.",
  curiosidad: "En Qatar 2022, Túnez logró vencer 1-0 a la futura campeona Francia, aunque no le alcanzó para avanzar a octavos de final."
},
{
  slug: "mali",
  pais: "Mali",
  bandera: "🇲🇱",
  confederation: "CAF",
  dt: "Tom Saintfiet",
  dtNacionalidad: "Bélgica",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 51,
  mundiales: 0,
  apariciones: 1,
  mejorResultado: "Fase de grupos (2026)",
  titulos: [],
  jugadores: [
    { nombre: "Yves Bissouma", posicion: "Mediocampista", club: "Tottenham", edad: 29, dorsal: 8 },
    { nombre: "Amadou Haidara", posicion: "Mediocampista", club: "RB Leipzig", edad: 28, dorsal: 6 },
    { nombre: "Mohamed Camara", posicion: "Mediocampista", club: "Mónaco", edad: 26, dorsal: 5 },
    { nombre: "Boubacar Traoré", posicion: "Mediocampista", club: "Wolves", edad: 24, dorsal: 13 },
    { nombre: "Djigui Diarra", posicion: "Portero", club: "Young Africans", edad: 30, dorsal: 1 }
  ],
  historia: "Las Águilas de Mali debutan en una Copa del Mundo en 2026, cumpliendo un sueño histórico tras décadas de generaciones talentosas. Son potencia en categorías juveniles africanas.",
  curiosidad: "Salif Keita, mejor futbolista africano de 1970, es la mayor leyenda de Mali, pese a no haber podido disputar nunca un Mundial."
},
{
  slug: "drc-congo",
  pais: "RD del Congo",
  bandera: "🇨🇩",
  confederation: "CAF",
  dt: "Sébastien Desabre",
  dtNacionalidad: "Francia",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 55,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Fase de grupos (Alemania 1974, como Zaire)",
  titulos: [],
  jugadores: [
    { nombre: "Chancel Mbemba", posicion: "Defensor", club: "Lille", edad: 31, dorsal: 4 },
    { nombre: "Yoane Wissa", posicion: "Delantero", club: "Newcastle", edad: 29, dorsal: 9 },
    { nombre: "Cédric Bakambu", posicion: "Delantero", club: "Real Betis", edad: 34, dorsal: 11 },
    { nombre: "Théo Bongonda", posicion: "Extremo", club: "Spartak Moscú", edad: 30, dorsal: 7 },
    { nombre: "Lionel Mpasi", posicion: "Portero", club: "Rodez", edad: 31, dorsal: 1 }
  ],
  historia: "La RD del Congo, conocida como Zaire en 1974, fue la primera selección del África subsahariana en un Mundial. Vuelve al escenario mundial tras 52 años de ausencia.",
  curiosidad: "En el Mundial de 1974, el defensa Mwepu Ilunga salió del muro a despejar un tiro libre antes del pitido del árbitro, una de las escenas más insólitas en los Mundiales."
},
{
  slug: "corea-del-sur",
  pais: "Corea del Sur",
  bandera: "🇰🇷",
  confederation: "AFC",
  dt: "Hong Myung-bo",
  dtNacionalidad: "Corea del Sur",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 24,
  mundiales: 0,
  apariciones: 12,
  mejorResultado: "Cuarto lugar (Corea-Japón 2002)",
  titulos: [],
  jugadores: [
    { nombre: "Son Heung-min", posicion: "Delantero", club: "LAFC", edad: 33, dorsal: 7 },
    { nombre: "Kim Min-jae", posicion: "Defensor", club: "Bayern Múnich", edad: 29, dorsal: 4 },
    { nombre: "Lee Kang-in", posicion: "Mediocampista", club: "Paris Saint-Germain", edad: 25, dorsal: 18 },
    { nombre: "Hwang Hee-chan", posicion: "Delantero", club: "Wolves", edad: 29, dorsal: 11 },
    { nombre: "Cho Hyun-woo", posicion: "Portero", club: "Ulsan HD", edad: 34, dorsal: 1 }
  ],
  historia: "Corea del Sur llegó a semifinales como anfitriona en 2002 bajo el mando de Guus Hiddink, hito histórico para el fútbol asiático. Es la selección asiática con más participaciones mundialistas.",
  curiosidad: "Corea del Sur tiene su servicio militar obligatorio, del que Son Heung-min se libró tras ganar los Juegos Asiáticos 2018 con la selección olímpica."
},
{
  slug: "arabia-saudita",
  pais: "Arabia Saudita",
  bandera: "🇸🇦",
  confederation: "AFC",
  dt: "Hervé Renard",
  dtNacionalidad: "Francia",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 60,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Octavos de final (Estados Unidos 1994)",
  titulos: [],
  jugadores: [
    { nombre: "Salem Al-Dawsari", posicion: "Extremo", club: "Al-Hilal", edad: 34, dorsal: 10 },
    { nombre: "Mohamed Kanno", posicion: "Mediocampista", club: "Al-Hilal", edad: 31, dorsal: 23 },
    { nombre: "Firas Al-Buraikan", posicion: "Delantero", club: "Al-Ahli", edad: 25, dorsal: 9 },
    { nombre: "Ali Al-Bulaihi", posicion: "Defensor", club: "Al-Hilal", edad: 36, dorsal: 5 },
    { nombre: "Mohammed Al-Owais", posicion: "Portero", club: "Al-Hilal", edad: 34, dorsal: 21 }
  ],
  historia: "Los Halcones Verdes debutaron en Estados Unidos 1994 llegando a octavos. En Qatar 2022 dieron una de las mayores sorpresas mundialistas al vencer 2-1 a Argentina, futura campeona.",
  curiosidad: "El día siguiente a la victoria sobre Argentina en Qatar 2022, el rey saudí decretó feriado nacional para celebrar la histórica gesta."
},
{
  slug: "australia",
  pais: "Australia",
  bandera: "🇦🇺",
  confederation: "AFC",
  dt: "Tony Popovic",
  dtNacionalidad: "Australia",
  color: "bg-yellow-700",
  colorHex: "#a16207",
  rankingFIFA: 26,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Octavos de final (2006, 2022)",
  titulos: [],
  jugadores: [
    { nombre: "Mat Ryan", posicion: "Portero", club: "Lens", edad: 33, dorsal: 1 },
    { nombre: "Mitchell Duke", posicion: "Delantero", club: "Machida Zelvia", edad: 35, dorsal: 15 },
    { nombre: "Jackson Irvine", posicion: "Mediocampista", club: "St. Pauli", edad: 32, dorsal: 22 },
    { nombre: "Harry Souttar", posicion: "Defensor", club: "Sheffield United", edad: 27, dorsal: 19 },
    { nombre: "Riley McGree", posicion: "Mediocampista", club: "Middlesbrough", edad: 26, dorsal: 10 }
  ],
  historia: "Australia pertenece a la AFC desde 2006 y ha clasificado a todos los Mundiales desde entonces. Sus Socceroos llegaron a octavos en Alemania 2006 y Qatar 2022.",
  curiosidad: "Tim Cahill es el máximo goleador histórico de Australia y el único futbolista australiano en haber marcado en tres Mundiales diferentes."
},
{
  slug: "iran",
  pais: "Irán",
  bandera: "🇮🇷",
  confederation: "AFC",
  dt: "Amir Ghalenoei",
  dtNacionalidad: "Irán",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 20,
  mundiales: 0,
  apariciones: 7,
  mejorResultado: "Fase de grupos",
  titulos: [],
  jugadores: [
    { nombre: "Mehdi Taremi", posicion: "Delantero", club: "Olympiacos", edad: 33, dorsal: 9 },
    { nombre: "Sardar Azmoun", posicion: "Delantero", club: "Shabab Al-Ahli", edad: 30, dorsal: 20 },
    { nombre: "Alireza Jahanbakhsh", posicion: "Extremo", club: "Heerenveen", edad: 32, dorsal: 7 },
    { nombre: "Saeid Ezatolahi", posicion: "Mediocampista", club: "Esteghlal", edad: 29, dorsal: 5 },
    { nombre: "Alireza Beiranvand", posicion: "Portero", club: "Persepolis", edad: 33, dorsal: 1 }
  ],
  historia: "Irán es una de las potencias asiáticas con siete Mundiales disputados. Ha sido la selección asiática mejor rankeada por FIFA durante años recientes, sin lograr nunca pasar de fase de grupos.",
  curiosidad: "Irán protagonizó uno de los partidos más cargados políticamente de la historia al enfrentar a Estados Unidos en Francia 1998, victoria iraní 2-1."
},
{
  slug: "irak",
  pais: "Irak",
  bandera: "🇮🇶",
  confederation: "AFC",
  dt: "Graham Arnold",
  dtNacionalidad: "Australia",
  color: "bg-green-800",
  colorHex: "#166534",
  rankingFIFA: 57,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Fase de grupos (México 1986)",
  titulos: [],
  jugadores: [
    { nombre: "Aymen Hussein", posicion: "Delantero", club: "Al-Najma", edad: 30, dorsal: 9 },
    { nombre: "Zidane Iqbal", posicion: "Mediocampista", club: "Utrecht", edad: 23, dorsal: 8 },
    { nombre: "Ali Al-Hamadi", posicion: "Delantero", club: "Ipswich Town", edad: 23, dorsal: 11 },
    { nombre: "Rebin Sulaka", posicion: "Defensor", club: "Belenenses", edad: 32, dorsal: 4 },
    { nombre: "Jalal Hassan", posicion: "Portero", club: "Al-Shorta", edad: 31, dorsal: 1 }
  ],
  historia: "Irak debutó en México 1986 y vuelve a un Mundial 40 años después. Su mayor logro fue ganar la Copa Asiática 2007 en plena guerra, momento histórico para el país.",
  curiosidad: "La selección iraquí ganó la Copa Asiática 2007 en plena guerra civil, unificando momentáneamente a un país dividido por el conflicto."
},
{
  slug: "qatar",
  pais: "Qatar",
  bandera: "🇶🇦",
  confederation: "AFC",
  dt: "Julen Lopetegui",
  dtNacionalidad: "España",
  color: "bg-red-900",
  colorHex: "#7f1d1d",
  rankingFIFA: 52,
  mundiales: 0,
  apariciones: 2,
  mejorResultado: "Fase de grupos (Qatar 2022)",
  titulos: [],
  jugadores: [
    { nombre: "Akram Afif", posicion: "Extremo", club: "Al-Sadd", edad: 29, dorsal: 11 },
    { nombre: "Almoez Ali", posicion: "Delantero", club: "Al-Duhail", edad: 29, dorsal: 19 },
    { nombre: "Hassan Al-Haydos", posicion: "Mediocampista", club: "Al-Sadd", edad: 35, dorsal: 10 },
    { nombre: "Boualem Khoukhi", posicion: "Defensor", club: "Al-Arabi", edad: 35, dorsal: 16 },
    { nombre: "Meshaal Barsham", posicion: "Portero", club: "Al-Sadd", edad: 28, dorsal: 22 }
  ],
  historia: "Qatar organizó el Mundial 2022 y debutó como anfitrión, sin lograr puntos. Vigente bicampeón de la Copa Asiática (2019 y 2023), clasifica deportivamente por primera vez en 2026.",
  curiosidad: "Qatar es el primer país árabe en organizar una Copa del Mundo y el primer anfitrión en perder los tres partidos de fase de grupos."
},
{
  slug: "jordania",
  pais: "Jordania",
  bandera: "🇯🇴",
  confederation: "AFC",
  dt: "Jamal Sellami",
  dtNacionalidad: "Marruecos",
  color: "bg-red-800",
  colorHex: "#991b1b",
  rankingFIFA: 64,
  mundiales: 0,
  apariciones: 1,
  mejorResultado: "Fase de grupos (2026)",
  titulos: [],
  jugadores: [
    { nombre: "Musa Al-Taamari", posicion: "Extremo", club: "Montpellier", edad: 29, dorsal: 7 },
    { nombre: "Yazan Al-Naimat", posicion: "Delantero", club: "Al-Ahli Doha", edad: 27, dorsal: 9 },
    { nombre: "Mahmoud Al-Mardi", posicion: "Mediocampista", club: "Al-Faisaly", edad: 27, dorsal: 8 },
    { nombre: "Salem Al-Ajalin", posicion: "Defensor", club: "Al-Wehdat", edad: 27, dorsal: 4 },
    { nombre: "Yazeed Abulaila", posicion: "Portero", club: "Al-Hussein", edad: 32, dorsal: 1 }
  ],
  historia: "Jordania debuta en una Copa del Mundo en 2026 tras alcanzar la final de la Copa Asiática 2023, donde cayó ante Qatar. Vive el mejor momento futbolístico de su historia.",
  curiosidad: "El príncipe Ali bin Al Hussein de Jordania fue candidato a la presidencia de la FIFA en 2015 y 2016, enfrentándose a Sepp Blatter."
},
{
  slug: "uzbekistan",
  pais: "Uzbekistán",
  bandera: "🇺🇿",
  confederation: "AFC",
  dt: "Timur Kapadze",
  dtNacionalidad: "Uzbekistán",
  color: "bg-blue-800",
  colorHex: "#1e40af",
  rankingFIFA: 59,
  mundiales: 0,
  apariciones: 1,
  mejorResultado: "Fase de grupos (2026)",
  titulos: [],
  jugadores: [
    { nombre: "Eldor Shomurodov", posicion: "Delantero", club: "Roma", edad: 30, dorsal: 9 },
    { nombre: "Abdukodir Khusanov", posicion: "Defensor", club: "Manchester City", edad: 22, dorsal: 5 },
    { nombre: "Jaloliddin Masharipov", posicion: "Mediocampista", club: "Pakhtakor", edad: 32, dorsal: 10 },
    { nombre: "Abbosbek Fayzullaev", posicion: "Mediocampista", club: "CSKA Moscú", edad: 22, dorsal: 7 },
    { nombre: "Utkir Yusupov", posicion: "Portero", club: "Pakhtakor", edad: 30, dorsal: 1 }
  ],
  historia: "Uzbekistán debuta en una Copa del Mundo en 2026 tras varias campañas cercanas a la clasificación. Es considerada una potencia emergente en la AFC desde su independencia en 1991.",
  curiosidad: "Uzbekistán formó parte de la selección soviética hasta 1991 y se incorporó a la AFC tras la disolución de la URSS, jugando su primer partido oficial en 1992."
},
{
  slug: "nueva-zelanda",
  pais: "Nueva Zelanda",
  bandera: "🇳🇿",
  confederation: "OFC",
  dt: "Darren Bazeley",
  dtNacionalidad: "Inglaterra",
  color: "bg-slate-800",
  colorHex: "#1e293b",
  rankingFIFA: 86,
  mundiales: 0,
  apariciones: 3,
  mejorResultado: "Fase de grupos (1982, 2010)",
  titulos: [],
  jugadores: [
    { nombre: "Chris Wood", posicion: "Delantero", club: "Nottingham Forest", edad: 34, dorsal: 9 },
    { nombre: "Marko Stamenić", posicion: "Mediocampista", club: "Olympiacos", edad: 23, dorsal: 8 },
    { nombre: "Liberato Cacace", posicion: "Lateral", club: "Wolves", edad: 25, dorsal: 3 },
    { nombre: "Kosta Barbarouses", posicion: "Extremo", club: "Wellington Phoenix", edad: 35, dorsal: 11 },
    { nombre: "Alex Paulsen", posicion: "Portero", club: "Bournemouth", edad: 23, dorsal: 1 }
  ],
  historia: "Los All Whites son el rey indiscutido de Oceanía. En Sudáfrica 2010 firmaron una gesta inédita: terminar el Mundial invictos con tres empates, aunque sin pasar a octavos.",
  curiosidad: "Nueva Zelanda fue la única selección que terminó invicta el Mundial de Sudáfrica 2010, incluyendo un empate ante la campeona Italia."
}

];

export const FORMATO = {
  equipos: 48,
  grupos: 12,
  equiposPorGrupo: 4,
  clasificanPorGrupo: 2,
  mejoresTerceros: 8,
  totalFaseGrupos: 64,
  rondas: ["Fase de Grupos", "Ronda de 32", "Octavos", "Cuartos de final", "Semifinal", "Final"],
};
