[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Redirigir el subdominio antiguo de Netlify al dominio personalizado
[[redirects]]
  from   = "https://tablitasquinielas.netlify.app/*"
  to     = "https://tablitasquinielas.com/:splat"
  status = 301
  force  = true
